### ISSUE TITLE
Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by sritchie** [omcljs/om#115]
Hey @swannodette,

Bug report for you... or perhaps I'm structuring this the wrong way.

I'm working on a stopwatch application in Om 0.4. (code here: https://github.com/paddleguru/om-timer)

It looks like [implementing IWillMount with a go block that transacts the state](https://github.com/paddleguru/om-timer/blob/master/src/cljs/paddleguru/client/timer.cljs#L212) SOMETIMES causes the following exception in the JS console:

Uncaught TypeError: Cannot read property 'firstChild' of undefined 

The error's coming from the findComponentRoot function in React:

``` js
 findComponentRoot: function(ancestorNode, id) {
    var firstChildren = [ancestorNode.firstChild];
    var childIndex = 0;
    <elided>
}
```

If I remove the `IWillMount` go block, the error goes away. Also, if I add a couple of newlines then remove them and recompile, sometimes when I reload everything works great and there's no error (with no code change, just a recompilation).

As far as symptoms go:
- The Timer state change seems to be working great - I tossed a println into the go block that derefs and inspects the timingapp state, and I see three console printlines for every error. (Seems to be 3:1 every time.)
-  The "clock" rendering implementation always works, and the timer gets updated fine.
- On the runs where the error DOES appear, the "stop timer" "start timer" text `:value` doesn't change, even though the `:onClick` handler is doing what it's supposed to and toggling the `:active?` state:

https://github.com/paddleguru/om-timer/blob/master/src/cljs/paddleguru/client/timer.cljs#L251

I thought the problem might be with that lookup on the cursor, but commenting out the `:value` kv pair doesn't fix the issue.

Thanks for taking a look. Hope all this helps, and maybe uncovers something that needs fixing rather than just being my goof.

**Comment by VAS** [comment]
We struggled for hours with this issue. We had a component that had it's own node_modules including react...and this is exactly what fixed the issue. (webpack included the script twice)

Thanks! @sritchie @gasi

**Comment by gasi** [comment]
:+1: @STRML @VAS

**Comment by danevans** [comment]
We ran into this issue because we upgraded to Om 0.8.8 but we are also using Sablono and that was on 0.3.0. If you are using both they both need to use the same React. Otherwise you may get this 'firstChild" error.
