### ISSUE TITLE
Allow components to specify displayName

### ISSUE THREAD

**Issue by qbg** [omcljs/om#124]
Om components do not currently set the displayName property. As a result, the components show up as `Unknown` in the [React Dev Tools](http://facebook.github.io/react/blog/2014/01/02/react-chrome-developer-tools.html). This also affects the [diff algorithm](http://calendar.perfplanet.com/2013/diff/) as the components all appear to be the same to React.

**Comment by leonid-shevtsov** [comment]
What kind of patch do we need to get this issue resolved? displayName is still not being set using om 0.9.0 and react 0.13.3

**Comment by DeLaGuardo** [comment]
You can set displayName like this
```clojure
(reify
  om/IDisplayName
  (display-name [_]
    "Any name")))
```

**Comment by leonid-shevtsov** [comment]
Sure, but it doesn't work. I tried placing an `alert` into the function, and it is never called.

Here's my code:

```clojure
(defn feed-item [feed _]
  (reify
    om/IDisplayName
    (display-name [_] (js/alert "xxxxxx") "FeedItem")
    om/IRender
    (render [_]
       ; .... )))
```

**Comment by the-kenny** [comment]
I don't know why `alert' isn't called for you, but IDisplayName works
just fine for me.

Leonid Shevtsov <notifications@github.com> writes:

> Sure, but it doesn't work. I tried placing an `alert` into the function, and it is never called.
>
> Here's my code:
>
> ```clojure
> (defn feed-item [feed _]
>   (reify
>     om/IDisplayName
>     (display-name [_] (js/alert "xxxxxx") "FeedItem")
>     om/IRender
>     (render [_]
>        ; .... )))
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/omcljs/om/issues/124#issuecomment-135666994

--

**Comment by wilkerlucio** [comment]
Leonid, did you tried to use React chrome plugin to inspected the rendered
tree? I suspect that unless you try to actually see the the names the
method will not be called.

**Comment by leonid-shevtsov** [comment]
I found the problem - I was using the [beta React Developer Tools](https://facebook.github.io/react/blog/2015/08/03/new-react-devtools-beta.html) released this month. With the stable devtools everything works as expected. Sorry for the confusion.

(However, another app that I'm working on is written in ES6 and the display names there work. That why I had initially decided this issue is not resolved)
