### ISSUE TITLE
Intermediate tutorial in Chrome : neither React nor om.core/root defined

### ISSUE THREAD

**Issue by phtrivier** [omcljs/om#141]
Very strange things happening when trying to follow the Intermediate tutorial : 
- In Chrome ( 33.0.1750.149 ), the react-0.9.0.js file can't be downloaded properly (the CDN returns a 301, and there is a console error about 
  
  Resource interpreted as Script but transferred with MIME type text/html: "about:blank"
- Still, in Chrome, even evaluating the simplest code, the om/root function does not seem to be defined in the client !

```
(ns om-systems.core
  (:require [cljs.reader :as reader]
            [goog.events :as events]
            [goog.dom :as gdom]
            [om.core :as om :include-macros true]
            [om.dom :as dom :include-macros true])
  (:import [goog.net XhrIo]
           goog.net.EventType
           [goog.events EventType]))

(enable-console-print!)
(println om.core/root) ;; => nil
```

Things seem to work fine in Firefox. 
Any idea what could cause this ?

**Comment by Xempai** [comment]
I had that problem too, and guess what was responsible  : an extension called Disconnect.

**Comment by phtrivier** [comment]
Very likely (I use it too.) 
I had to disable all extension to get things working, and I never took the time to pinpoint the culprit. 
Since Disconnect tries to avoid FB monitoring, it probably blocks many things from fb domain. My bad.
