### ISSUE TITLE
I would like to contribute some branding for Om

### ISSUE THREAD

**Issue by juliankrispel** [omcljs/om#215]
**Disclaimer:** I'm only just getting into the ClojureScript world (from JavaScript) but it's all very exciting to me. 

I'd like to contribute some design work to the Om project, in whatever form helps, whether it'd be a logo or website or both. Not sure if this is the best way to start this process but here you go. Let me know what you think and maybe we can figure out a way I can be useful, I'd very much like to be!

**Comment by swannodette** [comment]
@juliankrispel not sure if you're still interested in pushing this along but I finally got around to creating a CA for this project. Send me an email and I will send it your way and we can get this process started. Sorry for the delays - lots of things keeping me busy these days as perhaps you can tell :)

**Comment by juliankrispel** [comment]
@swannodette of course I am interested. No worries at all. I'm fully aware of all the amazing clojurescript work you've been doing!

My email is julian [at] goodafternoon [dot] co. Looking forward to this!
