### ISSUE TITLE
Cursors need to have the ability to control how they read and write from state.

### ISSUE THREAD

**Issue by ckirkendall** [omcljs/om#265]
Currently, cursors use get-in and assoc-in on their path to reading and writing from state.  This limits the ability for more complex type of cursors.  If the path was something protocol based like https://github.com/ckirkendall/fresnel it would alow the support of transformations on the data.  Below is an example from one of our internal projects at Outpace.  It shows the use of a sql like language to query the app state and return a cursor like object that can be written back to.  Its basically a two way lens on the app state that operates like a cursor.

```clojure
(def app-state (atom {:options [{:id "1" :name "test1" :creative_type_id "2"}
                                {:id "2" :name "test2" :creative_type_id "1"}
                                {:id "3" :name "test3" :creative_type_id "1"}
                                {:id "4" :name "test4" :creative_type_id "2"}]
                      :creatives [{:id "1" :name "my creative" :type_id "1"}]}}))
                      
(let [ref (q 
            (select
              ;;construct builds a proxy cursor
              (construct {:value (?- ['op :id])
                          :description (?- ['op :name])})
              (from 
                (join [:options] 'op)
                (join [:creatives] 'c (on (eq (?- ['c :type_id])
                                              (?- ['op :creative_type_id]))))))
            (om/root-cursor app-cursor)]
      (om/transact! ref [0 :description] "test-updated")])

;;below is the state of app after the trasact is applied
#_{:options [{:id "1" :name "test1" :creative_type_id "2"}
             {:id "2" :name "test-updated" :creative_type_id "1"}
             {:id "3" :name "test3" :creative_type_id "1"}
             {:id "4" :name "test4" :creative_type_id "2"}]
   :creatives [{:id "1" :name "my creative" :type_id "1"}]}
```

**Comment by swannodette** [comment]
Closing this one for now. I have some fairly significant thoughts about the future direction of Om towards a Relay-like design which will address this. The intention is to fully maintain backwards compatibility but I'm unlikely to continue enhancing the old model.
