### ISSUE TITLE
New warnings with React 0.12.0

### ISSUE THREAD

**Issue by danielsz** [omcljs/om#273]
Hi, 

I would like to report new warnings I'm seeing in the browser console after upgrading to React 0.12.0.
- React.render / React.renderComponent

``` sh
Warning: React.renderComponent will be deprecated in a future version. Use React.render instead. 
```
- React legacy factory

``` sh
Warning: Something is calling a React component directly. Use a factory or JSX instead. 
```

Everything seems to work fine though.

The old messages regarding missing keys were more helpful, because they included a hint as to which call the culprit. Now it only says:

``` sh
Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined. 
```

Which gives me a hell of a time to track the source of the problem.

**Comment by kernelp4nic** [comment]
I know this is an old thread, but I'm having the same warnings using the latest version of om (wich depends on 0.12.2)

Any thoughts?
