### ISSUE TITLE
Simplify passing child nodes to Om Component

### ISSUE THREAD

**Issue by thheller** [omcljs/om#291]
One Om Component I wanted to write grew out of a simple Wrapper function (using sablono for simplicity, same goes for ```om.dom```):

```clojure
(defn my-wrapper [title & contents]
  (html
   [:div.box
    [:h1 title]
    contents]))

(my-wrapper "Hello World"
  (html [:div.fancy-content]))
```

I wanted to turn my-wrapper into an Om component itself but passing child nodes is confusing and requires using ```(om/build my-wrapper cursor {:opts {:children [manual-labor]}))```.

We could change the signature of 'om.core/build to

```(defn build [f x m & children])``` and then pass the children to either ```f``` or ```om.core/IRender(State)```

```clojure
(defn my-wrapper [cursor owner & contents]
  (reify ...)

;; OR

(defn my-wrapper [cursor owner]
  (reify
    om/IRender
    (render [_ contents] ;; no var-arg, but can destructure
      ...)))

(om/build my-wrapper cursor {}
  (html [:div.fancy-content]))
```

Unless this is something totally bad and wrong.

I would be happy to provide a patch to enable this.

---

I don't quite understand the design choice to use the ```this.props.children``` property to pass the Om Component, is there some special handling of React that requires this? Using a "regular" ```:__om_component``` prop together with "real" children seems more appropriate?

One complication might be ```.shouldComponentUpdate```, not sure in which order React calls them and if they are called at all if ```my-wrapper.shouldComponentUpdate``` returned false. Using ```:opts``` does not address this in any case though so we should be fine.

Thoughts?

**Comment by thheller** [comment]
FWIW I did some investigation into this and currently this is very impractical.

```shouldComponentUpdate``` would need to check ```children``` and since that is an array of React-Nodes which don't exactly support ```IEquiv``` that is questionable. It can be done but not sure it is worth it. Would be nice if ``` ReactElement``` was ```(deftype ReactElement [...])``` but we can only dream.

**Comment by swannodette** [comment]
Closing this one.

**Comment by razum2um** [comment]
why so?

**Comment by swannodette** [comment]
@razum2um not going to address it in the old model.

**Comment by Peeja** [comment]
@swannodette Sorry, can you elaborate on what that means? Do you mean this will be covered in the move to React 0.13?

**Comment by JulianLeviston** [comment]
@Peeja no, it means he's in the process of remodelling how Om works, and this issue relates to the old way things worked. There's a branch called "next" that may be that work.

**Comment by Peeja** [comment]
Cheers! That's really what I meant; the rework of Om will (if I understand correctly) depend on React 0.13.

I was looking for more concrete info on that future Om version. I don't know why I didn't think to look for an obvious branch. :p Thanks.
