### ISSUE TITLE
Question: Do components need to be coupled with cursors?

### ISSUE THREAD

**Issue by rads** [omcljs/om#303]
It seems that much of the complexity of Om comes from these two facts:
1. When a component _reads shared application data_, it retrieves it from a cursor that was provided by the parent component.
2. When a component _changes shared application data_, it reuses these same cursors to convey the new state.

Since cursors are similar to zippers, we try to represent the application state as a tree to make it easy to distribute the cursors down to the components. The writes take effect on the same location the component is reading from, so cursor represents a simple two-way data flow at that location in the app state tree. This works great when the reads and writes happen all in the same place.

This model falls apart when the component wants to convey the writes in different way than the reads. Let's say we have a todo list stored in a [DataScript](https://github.com/tonsky/datascript) database, which is like Datomic but only in-memory in the browser. Our application state is now a database, not a tree, but we probably want to convert it to a tree before passing it down into the components so that each component does not have to take the entire database as a prop. The transformation would look something like this:

```
;; todo list represented as datoms
;; [entity-id attribute value transaction-id]
[[1 :item/title "First Todo" 123]
 [1 :item/completed false 123]
 [2 :item/title "Second Todo" 123]
 [2 :item/completed true 123]
 [3 :list/title "My Todo List" 123]
 [3 :list/selection 1 123]]

;; same todo list represented as a tree
{:id 3
 :title "My Todo List"
 :items [{:id 1
          :title "First Todo"
          :completed false
          :selected true}
         {:id 2
          :title "Second Todo"
          :completed true
          :selected false}]}
```

At this point we have _denormalized_ the original data because there is only _one_ `:list/selection` datom, but _many_ `selected` attributes. This makes the data easier to use in our application because the `TodoItem` component can accept a single todo item map instead of the entire application state to see if its currently selected.

The problem is when we want to convey a change from the `TodoItem` component, such as selecting it on a click event, cursors force us to express the change as an operation on the same location that was passed down. While the tree structure above is natural for reading, there's no way for one `TodoItem` to change the `selected` attribute of the other `TodoItem` components unless we pass down the entire tree as a prop to each `TodoItem`. This is not what we want because it couples the low-level components with the structure of our entire application.

Even if we say screw it, let's just pass down the whole tree, we're forced to write extra code to observe the cursor transactions on the tree, then convert them into Datomic transactions. Let's say the user selects the second todo item, resulting in a new tree:

```
{:id 3
 :title "My Todo List"
 :items [{:id 1
          :title "First Todo"
          :completed false
          :selected false}
         {:id 2
          :title "Second Todo"
          :completed true
          :selected true}]}
```

Note that the `:selected` attribute is now `false` for the first todo, and `true` for the second. At this point we have not updated the true source of data in DataScript, so we have to write a function that compares the old state with the new to figure out what transactions we need to send. The resulting transaction would look like this:

```
{:db/id 3
 :list/selection 2}
```

This is all we need, but since we're using cursors, we cannot convey this change directly. It has to happen as a result of the cursor transactions and then we have to suss it out using `:tx-listen` with logic to detect that the `:selected` attributes above got changed. This is way too complicated for such a simple operation!

I propose an alternative: why not decouple the way the data is read from the way it is written? We could pass the data each component needs as plain Clojure data types (vectors, sets, maps) for reading, using regular props and the same convenient tree structure I showed above. The difference is when we need to convey a change, we could represent it as a reified event:

```
{:action :select-item
 :item-id 2}
```

We can take this event and put it on a channel, which could also be passed in as a prop.

It would be up to the application developer to implement something that takes events from the channel and converts them into changes to the application data. We could write a trivial function to convert the event into a Datomic transaction:

```
(defn select-item-event->transaction [list-id event]
  {:db/id list-id
   :list/selection (:item-id event)})
```

This code would be specific to each application, but it's shorter than the code necessary to detect the equivalent changes in the tree from `:tx-listen`. With this architecture, cursors are no longer necessary.

This is a similar idea to Facebook's [Flux](http://facebook.github.io/flux/docs/overview.html) architecture for React applications. In the Flux architecture, the app state is passed down as plain JavaScript objects, and all events are sent to a dispatcher that coordinates the changes. The big difference is they store the app state in bunch of mutable objects instead of a single mutable reference like Om has. That's a mistake, but the dispatcher could just as easily function like a transactor in Datomic where it only coordinates changes from events and delegates out business logic and storage to other parts of the system.

I don't doubt that you've put a lot of thought into this, @swannodette. Is there a big disadvantage to doing it this way that I'm missing?

**Comment by ioRekz** [comment]
Google pointed me while looking for "reified mutations". This is almost 1 year old but very relevant with om next ! Interesting read ...
