### ISSUE TITLE
Rename om/update! to om/set!, om/update-state! to om/transact-state!

### ISSUE THREAD

**Issue by lgrapenthin** [omcljs/om#312]
As a long time om user even after more than half a year I get `set-state!`, `update-state!`, `update!` and `transact!` mixed up. It doesn't go away because it simply doesn't become an intuitive thing to go with. Every two days or so, I feel the need to look them up, safety-check during coding or fix them during dynamic development. This clearly is in the way of thinking domain-related.

Assuming that I am not alone with this, my proposal is to rename `om/update!` to `om/set!` and `om/update-state!` to `om/transact-state!` so that I have to know effectively two words (`set!` and `transact!`) for two operations (instead of having to remember three words where one means both operations and the other mean one each):

The resulting API would be:

thing/op | set | swap
--- | --- | ---
cursor | `om/set!` | `om/transact!` 
component (local state) | `om/set-state!` | `om/transact-state!`

(Obviously, this would be a non-breaking change.)

**Comment by ioRekz** [comment]
I get confused as well and this api would help me

**Comment by pleasetrythisathome** [comment]
+1, although why not just swap! and swap-state!?

**Comment by brianru** [comment]
+1

**Comment by swannodette** [comment]
Will think about it.

**Comment by kendru** [comment]
+1 - I seem to forget this one whenever I go a few days without touching the om app I'm working on

**Comment by swannodette** [comment]
Please stop +1'ing. I get it and adding more votes doesn't mean it's going to happen. Thanks.

**Comment by swannodette** [comment]
No further enhancements will be considered for the old model.
