### ISSUE TITLE
Trying to `observe` multiple reference cursors ignores all but the first?

### ISSUE THREAD

**Issue by jmandel** [omcljs/om#319]
I have a component that tries to do something like:

```
(defn calculate-dependencies [topics]
  (reduce (ƒ [topic-map t]
            (assoc topic-map t (om/ref-cursor (cursor-for t))))
          {} topics))

(defn topics-component [topics owner]
  (reify
    om/IRender
    (render [_]
      (let [topic-cursor-map (calculate-dependencies topics)]
        (doall (map (partial om/observe owner)  (vals topic-cursor-map)))
        (dom/div nil "[Render my component...]")))))
```

But I find that only one dependency is actually established, on the first value in `(vals topic-cursor-map)`. The others are ignored.

Is this a known issue?

I'm using:

```
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2665"]
                 [com.facebook/react "0.12.2"]
                 [org.om/om "0.8.1"]]
```

**Comment by the-kenny** [comment]
Josh Mandel <notifications@github.com> writes:

> (map (partial om/observe owner (vals topic-cursor-map)))

Wrong parentheses here. Should be:

(map (partial om/observe owner) (vals topic-cursor-map))

**Comment by jmandel** [comment]
Thanks. This was just a typo in the example code I sketched out for the issue report. I have fixrf it above. The issue is still present, though.

**Comment by swannodette** [comment]
@jmandel please add a complete minimal example that can be tested thanks.

**Comment by jmandel** [comment]
Sure. The problem turns out to be that a component's `__om_refs` are stored as a set. When a component depends on two different `ref-cursors` that have the same initial value, we get:

```
(defn add-ref-to-component! [c ref]
  (let [state (.-state c)
        refs  (or (aget state "__om_refs") #{})]
    (when-not (contains? refs ref)
      (aset state "__om_refs" (conj refs ref)))))
```

Which is a problem when you initialize multiple distinct cursors to the same default value -- the first one gets added to the set, and others skip it (`contains?` returns true).

Example at:
https://github.com/jmandel/om/blob/master/examples/test_refs/src/core.cljs

(Pressing "Update B" doesn't trigger a re-render.)

**Comment by swannodette** [comment]
@jmandel hrm, not a use case I had accounted for. Do all your ref cursors also share the same path? I think perhaps refer cursors should implement `IHash` and `IEquiv` based on both `value` and `path`.

**Comment by jmandel** [comment]
If I understand your question correctly, then no my ref cursors don't all share the same path (e.g. in the example I gave one is at [:topics :a] and the other at [:topics :b]).

To avoid surprises, it would be nice to take root, path, and value all into account.

**Comment by swannodette** [comment]
@jmandel I'm not convinced about adding the additional complexity by allowing of completely different roots. Om is fundamentally a single source of truth model. Unless you're talking about something else?

**Comment by jmandel** [comment]
That was what I had in mind yes. I'm fine with saying "single root" across a whole app, but it wasn't entirely clear to me from the docs + examples that this philosophy extends to ref cursors. Assuming it does, then your assessment makes sense :-)

**Comment by swannodette** [comment]
There's just not a nice clean fix for this as it's currently implement (and the implementation is already too finicky). Om Next provides a more general solution to the cursor observation issue and we're going to dedicate our effort there instead.
