### ISSUE TITLE
investigate Om components that can be constructed without `om.core/build`

### ISSUE THREAD

**Issue by swannodette** [omcljs/om#322]
React 0.13 beta allows us to supply our own classes. We can probably move build boilerplate into the constructor function.

**Comment by dignati** [comment]
That would be great! To avoid calling om/build every time I currently wrap components in functions that do that for me but this sounds much better!

**Comment by weavejester** [comment]
I've been investigating ways of replacing Om's cursors with a non-hierarchical in-memory database. Would moving build boilerplate to the constructor function mean that cursors would be unavoidable?

**Comment by weavejester** [comment]
Ah, nevermind. I mistakenly thought that cursors were initiated by `build`, but I see it's initiated by `root`.

**Comment by swannodette** [comment]
This is going to be a part of the new model. Not going to track it for now.
