### ISSUE TITLE
Observe non-existant paths

### ISSUE THREAD

**Issue by dignati** [omcljs/om#328]
It would be great if we could observe a reference cursor to a path that does not exist yet in the app-state. That way we could observe while waiting for server responses etc.

The way I do it now is to observe a shorter path higher up in the app state if the path is not present yet.

**Comment by JulianLeviston** [comment]
You can do this by putting a blank map in place. That's how I do this.

**Comment by dignati** [comment]
Yes, I do that for simple cases but sometimes the path is so dynamic that
it's hard to keep track of where I need to put empty maps. It feels like a
hack to me.
Am 10.02.2015 18:43 schrieb "JulianLeviston" <notifications@github.com>:

**Comment by swannodette** [comment]
Not going to do this.
