### ISSUE TITLE
Multifunctions that despatch on keywords

### ISSUE THREAD

**Issue by bensu** [omcljs/om#329]
I have a minimal working [example](https://github.com/bensu/om-keyword-test) of a potential bug: if I feed to `om.core/build` a mutlimethod that dispatches on a bare keyword *and* an `opts` map, at some point Om tries to call the keyword with 3 arguments and it fails with "Invalid Argument arity: 4". I could trace the call that raises the exception to `om.core/getf` [here](https://github.com/omcljs/om/blob/master/src/om/core.cljs#L894). 

The relevant code:

```clj
(defmulti greeter :name)
...
(om/build greeter cursor {:fn identity})
```

One solution is to check if the function is a keyword before calling it with those arguments. In case you think it's the right solution, [here](https://github.com/bensu/om/compare/debug-defmulti-keyword) is the code. I know you don't take pull requests :)

Hope this helps

**Comment by the-kenny** [comment]
Not sure what's the issue here. ```om/build``` clearly states that it takes a three-arg fn. Your ```greeter``` only accepts one. Try ```(defmulti greeter (fn [c owner opts] (:greeter c)))```

**Comment by bensu** [comment]
A couple of things:

`om.core/build` needs `f` to be "a function of 2 or 3 arguments."

`greeter` accepts two arguments but it only dispatches on the first one. Yes, I could fix it with your suggestion but I find it common practice to use a naked keyword to dispatch on the first argument. Now, my perception of common practice can be very mistaken :) If that is the case, I'll close this immediately. A more complete snippet:

```clj
(defmulti greeter :name)

(defmethod greeter :kenny
   [data owner]
   ....)

(om/build greeter cursor {:fn identity})
```

**Comment by the-kenny** [comment]
Your ```greeter``` doesn't work like you expect: Keywords accept one or two args (see https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/core.cljs#L2508) but not three. So you dispatch *either* on the first value *or* on the second iff the first is ```nil``` (because the second arg to a keyword used as a function is the default value). I don't find that very intuitive.

I think the basic issue here is that the docstring of ```build``` should be updated. Reading ```build*```, it seems that the function MUST accept two *and* three args. (See https://github.com/omcljs/om/blob/master/src/om/core.cljs#L949 & https://github.com/omcljs/om/blob/master/src/om/core.cljs#L953)

**Comment by bensu** [comment]
That is exactly the behavior I expect. Dispatch on the first one. If the first one is `nil` nothing will ever work anyway, so it's fine if it fails by trying this `(:keyword first-argument second-argument)`

As for the docstring I think it is fine: `f - is a function of 2 *or* 3 arguments.` and as you correctly pointed out, the `build*` checks which arity it should call, and it never calls *both*. But it if you find it unclear, better to err on the side of more documentation :)

I think the issue is if this code:

```clj
(defmulti greeter :name) 
(defmethod greeter :keeny
   [data owner]
   ....)
```

is valid / desirable / good-practice ClojureScript code or not. If it is, I think Om should support it. If it's not, I'll make sure I change my code and document this somewhere so every else who upgraded Om (from pre 0.8.0 to post 0.8.0) and used this keyword dispatching style knows what to do about it.

**Comment by the-kenny** [comment]
It doesn't check if the function takes one or two args. It calls two args if ```opts``` is nil and three if not. If you pass ```:opts``` to ```om/build``` you HAVE to provide a three-arg fn.

**Comment by bensu** [comment]
Yes, that is correct. If you want to use the three arity `build` you have to supply a three arity `f`.
