### ISSUE TITLE
A component f is forever-coupled to the first descriptor that touched it

### ISSUE THREAD

**Issue by mrcslws** [omcljs/om#330]
I'm adding instrumentation, very similar to https://dwwoelfel.github.io/instrumenting-om-components.html

On a hotkey, I re-run `om/root` for each of my roots that I want instrumented, this time with a custom descriptor. And... nothing changes. The custom descriptor is not actually used.

I can work around the issue by always instrumenting everything, but that's not great. Also, it instruments it across all roots! So if I want a component to be instrumented here, but not there, I'm out of luck. This can be bad when I want to use a component in my app *and* inside of my perf dashboard, because the dashboard starts measuring its own performance, which has infinite-rerender potential.

Rather than putting the descriptor on the `f` object, have you considered storing an associative `{f1 descriptor1 f2 descriptor2}` in the parent component's `.-state`? And then just special-casing for the root component? Then `om/build*` would just read and write this map. I think that would solve most of these problems, localizing the descriptor and discarding them on unmount.

Here, I went ahead and hacked it together: https://github.com/mrcslws/om/commit/ef82988eed3da5ad80b6d731d677d8fc8f343e5f

**Comment by mrcslws** [comment]
I was going for a minimal change. Issues that I can think of:
- It doesn't completely fix the issue. The `[f owner]` is now forever-coupled, rather than just the `f`. Could solve this by associating it with `[f (or descriptor *descriptor* pure-descriptor)]` rather than just `f`, though in this scenario it might be a different descriptor instance each time. e.g. when a component decides to `om/build`an instrumented child component. This change does completely fix the `om/root` scenario, just not `om/build`.
- In cases where someone is doing something wrong like using an anonymous `f`, this will cause the atom to grow on every render.

**Comment by bensu** [comment]
I'm also trying to figure out "selective instrumentation". From the users perspective, I thought it would be *convenient* to opt-out of instrumentation in the `m` map of `build`. I don't know if it's good design though. Is [this](https://gist.github.com/bensu/6b08d7a78dd68c60fcfb) the type of code you wanted to write? (the Gist doesn't work)

**Comment by mrcslws** [comment]
@bensu so far I haven't felt the need to use `:instrument`. It's useful when you want to transform the built component, but it seems unnecessary when you're only specifying a descriptor. E.g. with your code, if I wanted to specify whether to instrument on each `om/build`, I'd just pass a descriptor in directly and skip the `:instrument`. I'd probably `def` an instrumented and a non-instrumented descriptor, and just choose one for each build.

You'd still run into this Issue. The first time an `f` is consumed, its descriptor would be forever-locked-in.

**Comment by bensu** [comment]
Thanks, to define an instrumented and uninstrumented version and then choose according to the build is a great idea. 

What you said about descriptors being locked in is best illustrated by changing:

```clj
(om/build display-counter data)
(om/build display-counter data {:opts {:instrument? false}})
```

to this

```clj
(om/build display-counter data {:opts {:instrument? false}
(om/build display-counter data)
```
and seeing how both counters behave in the same way, depending on what the first had for `opts`.

I'll do an experience report when (if) I settle on a way to handle conditional instrumentators.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/cc22d7ebdeb3108efb6fff1af49369dcf28363c0
