### ISSUE TITLE
Double will-unmount with no-local-state

### ISSUE THREAD

**Issue by brandonbloom** [omcljs/om#332]
It seems like the internal implementation of `componentWillUnmount` is called twice for the same component when using the experimental no-local-state descriptor. During the first call, the `IWillUnmount` protocol is not satisfied, but the state is removed. On the second call, `will-unmount` is called on the component, but `get-state` calls return nil.

I added some print statements in this branch:
https://github.com/brandonbloom/om/tree/double-will-unmount

I've got a component that sets the `:frontend.scroll/scroll-id` key in state and when it gets unmounted I see this output:
```
maybe will-unmount .0.2.2.0.0.3
clearing state from .0.2.2.0.0.3 was: {:render-state {:frontend.scroll/scroll-id 5}}
maybe will-unmount .0.2.2.0.0.3
satisfied will-unmount:  .0.2.2.0.0.3
clearing state from .0.2.2.0.0.3 was: nil
```

As best I can tell, this is reproducible with any stateful component that has a will-unmount and using the no-local-state descriptors.

**Comment by swannodette** [comment]
Warning no-local-state users should expect some churn. React 0.13 now hides _rootNodeId.

**Comment by swannodette** [comment]
Happy to revisit this one now that the no local state feature looks like it can survive the 0.13 churn. Patch welcome :)

**Comment by brandonbloom** [comment]
@swannodette Can you fill me in on what changed / didn't in 0.13 with respect to _rootNodeId?

**Comment by swannodette** [comment]
@brandonbloom 0.13 dropped `_rootNodeId` from public access. Currently on master we just wait until the component mounts to get this out of the DOM. There are some issues with this approach of course but perhaps good enough to support serialization / deserialization of the full application state for debugging purposes. If you see big problems with this approach happy to hear about it.

**Comment by brandonbloom** [comment]
Hm, that *might* work out OK, but places some pretty big restrictions on when you can read/write state. In particular, it means you can't read state unless you always read from the getInitialState result until mounting occurs. That might be good enough for reads if carefully implemented, but I'm not sure.

As an alternative idea: What about just making every underlying react component stateful and putting a unique ID in to the state? I don't know enough about the specifics of the state implementation to know the impact, but don't you already do something like that with props? Assuming there's not substantial perf impact, it seems sufficient to (comp assoc-in-a-unique-id get-initial-state) for all components.

**Comment by swannodette** [comment]
Om Next will have a way to externalize local state without relying on React internals. Making it work in the model is not effort I'm going to expend.
