### ISSUE TITLE
get-node should probably return nil if ref cannot be found

### ISSUE THREAD

**Issue by weavejester** [omcljs/om#339]
The two argument form of `get-node` currently looks like:

```clojure
(defn get-node [owner name]
  (when-let [refs (.-refs owner)]
    (.getDOMNode (aget refs name))))
```

This will result in a error if the name of the ref doesn't exist yet:

    Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

Perhaps instead `nil` could be returned:

```clojure
(defn get-node [owner name]
  (some-> (.-refs owner) (aget name) (.getDOMNode)))
```

Since the function already has a `when-let` in there, I assume this is in line with the intention of the code.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/803ce2408e3daf34fc2cb6e0219644ff995b7b6a
