### ISSUE TITLE
Log a warning when trying to render a lazy sequence

### ISSUE THREAD

**Issue by danielcompton** [omcljs/om#341]
I know the docs are clear on not being able to render lazy sequences, but I wondered if we could improve the experience by logging a warning when trying to render a lazy sequence. Would this be a useful feature?

Relates to #246

**Comment by danielcompton** [comment]
Put another way, is it ever correct to render a lazy sequence? I'm pretty sure that's a no. One consideration though is the performance impact of checking this.

**Comment by swannodette** [comment]
There's nothing wrong with rendering lazy sequences.

**Comment by danielcompton** [comment]
I don't think I explained this very well, I'm referring to 

> This means you should never put lists or lazy sequences into the application state. It's particularly easy to forget this when updating indexed sequences in the application state

From https://github.com/omcljs/om/wiki/Basic-Tutorial. Should there be a warning when Om tries to render a component from a list of lazy sequence in the app state?

**Comment by swannodette** [comment]
@danielcompton Om is not going to validate your data structures. There are plenty of good tools already to do this, use pre & post conditions.
