### ISSUE TITLE
Creating a sub-component with partial application leads to parent cursor "capture"

### ISSUE THREAD

**Issue by abailly** [omcljs/om#344]
Hello,
I have a UI with nested components where of course subcomponents are linked with sub-cursors passed down the hierarchy from top-level root cursor. I encountered a somewhat odd behaviour. When I do the following:

```
(om/build (partial approving-view source sink (:facId facility) (:facBrwId facility)) (-> facility :facState :facApprovedTerms))
```

i.e. building the subcomponent view through partial application, the parent component is re-rendered each time the sub-cursor is changed by sub-component, which leads to strange behaviours in the UI like input fields losing focus or part of the UI disappearing.

After couple of hours working on it I finally tracked the problem down to the `(partial ...)` form use. When I remove the partial form, things are working fine. I rewrote the above with the following:

```
(om/build approving-view (get-in facility [:facState :facApprovedTerms]) {:state {:callback #(om/set-state! owner :state :start) :source (:source state) :sink (:sink state) :fid fid  :bid bid}} )
```

I initially thought this was because I was passing the parent `owner` directly to its child as a way to communicate (the sub-component needs to "close" itself when done, which is implemented in the parent as a case on internal state) with it and I followed the advices given [here](https://groups.google.com/forum/#!searchin/clojurescript/om$20partial/clojurescript/H_M1GzFM78U/bOErWMlUnd4J) to reach my final implementation. But even removing that issue from the picture and trimming the code to bare minimum without parent/child communication I observed same behaviour.

Am I missing something?

**Comment by swannodette** [comment]
You really should never use anything but top level functions to build components. There's no intention in supporting anything else.

**Comment by abailly** [comment]
Is this documented somewhere? Or can I contribute some piece of documentation somewhere to highlight that fact so that other newbies like me don't get caught in that trap?
