### ISSUE TITLE
Can only observe cursors that implement IOmRef

### ISSUE THREAD

**Issue by thickey** [omcljs/om#346]
Cursors that are created with `get` or `get-in` are not able to be observed the way those created by `om/ref-cursor` can be.

The symptom of using a non-ref-cursor in this way results in errors such as:

> Uncaught Error: No protocol method IOmRef.-add-dep! defined for type om.core/MapCursor: [object Object]

The commit referenced below adds a new precondition to ensure that the cursor passed to `om/observe` satisfies the `IOmRef` protocol. I found this helpful for understanding what was going wrong.

https://github.com/thickey/om/commit/ee14fb91297fbda88b8b0f556aa682e4814e1c73

**Comment by swannodette** [comment]
Good idea and an easy enhancement.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/9a47b3479a4a7acbccab0ed2d7df8ca6e808c2c7
