### ISSUE TITLE
`raf` is not overridable when `js/requestAnimationFrame` is not available

### ISSUE THREAD

**Issue by sfnelson** [omcljs/om#347]
```
(cond
  (or (false? raf)
      (not (exists? js/requestAnimationFrame)))
  (js/setTimeout #(render-all state) 16)

  (fn? raf)
  (raf)

  :else
  (js/requestAnimationFrame #(render-all state)))
```

It's useful to be able to override (mock) raf for testing redraw behaviour, but this implementation does not allow overriding raf when `requestAnimationFrame` does not exist.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/6f2cde696068d823a0109dc120a14187d66d9740
