### ISSUE TITLE
get-ref

### ISSUE THREAD

**Issue by afhammad** [omcljs/om#349]
get-node assumes we are trying to get at the DOM node however at times it is useful to access the component class as you would in JS React by doing 
````
this.refs.componentName
````
 The scenario I need this in is when using components written in plain JS rather than CLJS Om and I am trying to get at a function in that class, for example:

````
this.refs.dialog.show()
````
I can get around this by doing 
````
(some-> (.-refs owner) (aget "dialog"))) 
````
Is there a better way of doing this?

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/c30f2b00c66a55fe5c15221aba594be3402f60e2

**Comment by afhammad** [comment]
Nice, thanks.
