### ISSUE TITLE
Compilation on windows produces invalid output

### ISSUE THREAD

**Issue by honzabrecka** [omcljs/om#354]
Hi, I'm compiling a clojurescript app (Om + target set to nodejs with optimzations none) on windows, but compiled output can't be run due to the following problem:

```js
// om/dom.js 4th line
cljs.core.load_file("resources\public\server\react.inc.js");
```

which should be:

```js
cljs.core.load_file("resources\\public\\server\\react.inc.js");
// or cljs.core.load_file("resources/public/server/react.inc.js");
```

**Comment by swannodette** [comment]
@honzabrecka this isn't an Om issue. Make sure you are on recent version of ClojureScript.
