### ISSUE TITLE
Component is not re-rendered on local state update if app-state does not notify watches on unchanged value

### ISSUE THREAD

**Issue by ul** [omcljs/om#355]
Minimal case is here: https://github.com/ul/om-local-state-re-render/blob/master/src/om_rerender_on_local_state_update/core.cljs

The problem is that when `app-state` is atom-like that notify its watches iff its value has been changed, component is not re-rendered on its local state update.

Try to press “change local state” — it will alter counter in local state, but no update happens on the screen. “change app state” triggers update.

Expected: altering local state will trigger re-render too.

**Comment by swannodette** [comment]
I would not consider this a bug. What is the actual use case?

**Comment by ul** [comment]
Use case is using Om with https://github.com/aaronc/freactive.core or another reactive library which provides atom-like types with slightly different from cljs.core/Atom behavior. Why Om depends on notifying state watches in the business of updating single component local state?

**Comment by swannodette** [comment]
@ul this is just out of scope for the current version of Om. Already possible in the next version of Om.
