### ISSUE TITLE
Integration with ReactDnD

### ISSUE THREAD

**Issue by bendlas** [omcljs/om#362]
ReactDnD (https://github.com/gaearon/react-dnd) doesn't work out of the box with om, because it uses at least 2 concepts not well supported in om:

- [ ] Higher Order Components (class decorators) as a more modern alternative to mixins, described here: https://github.com/omcljs/om/pull/361
- [ ] React props are used to propagate values to the DnD - enabled component

## Examples

A DnD Source: https://github.com/gaearon/react-dnd/blob/f251bc46549ab0d0887c043fddbb1945ddc83fd4/examples/01%20Dustbin/Single%20Target/Box.js#L32

Prop access: https://github.com/gaearon/react-dnd/blob/f251bc46549ab0d0887c043fddbb1945ddc83fd4/examples/01%20Dustbin/Single%20Target/Box.js#L44

**Comment by swannodette** [comment]
@bendlas class decorator support is probably not going to happen until Om Next and not interested in back porting it. As far the reliance on props seems like a bad design, that should be configurable at DnD.
