### ISSUE TITLE
Making defui* stable across reloads to maintain local state

### ISSUE THREAD

**Issue by bhauman** [omcljs/om#363]
When an component class identifier is redefined it loses it's local state on render.  This may not be desirable in a live development environment.

What is desired is a way to keep the identifier stable, i.e. defining the class once and only redefining the prototype members while keeping the main identifier stable.

But as developers its also nice to bypass this identifier stability and redefine the class to examine how things like getInitialState, statics etc. are working.

One solution is to have `defui` utilize `defonce` and have a `redefui` use `def` this has a nice live workflow experience.

Another solution is to return the class and have the developers decide how to define it.

Or all of the above.

**Comment by bhauman** [comment]
Actually, another way to approach this is with `defonceui` and `defui`

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/709e48edd0e6174f5840d1b3860ff506bd70f313
