### ISSUE TITLE
Which clojurescript version? 1.7.122? 1.7.48? 0.0-2760?

### ISSUE THREAD

**Issue by BertrandDechoux** [omcljs/om#371]
According to lein ancient, the last version is 1.7.122

According to clojurescript README, the last 'stable' version is 1.7.48

According to om README, the version that should be used is 0.0-2760

Could it be possible to at least explain the reason in the readme if it is intentional (and I guess it is)?

I am trying to update a one year old om project and I am a bit lost.

**Comment by swannodette** [comment]
Om is compatibility with any version of ClojureScript newer than the one in the README.

**Comment by BertrandDechoux** [comment]
Ok. Cool. Thanks.
