### ISSUE TITLE
S3 Direct Uploads with Progress

### ISSUE THREAD

**Issue by GetContented** [omcljs/om#372]
Would be nice for Om to get an updated direct-to-amazon-s3 library for integration into components, with upload progress, which I'm happy to contribute to (because I need it in my project). Would require a release of CLJS with a bump in the Google Closure library, though, because Google Closure only just added the progress functionality in to xhr a few days (week or two?) ago.

https://github.com/martinklepsch/s3-beam/issues/15

Apologies for cross-requesting this here, but I can't open tickets on CLJS's github repo, and it seems appropriate to Om & Reagent rather than CLJS proper.

Happy to close this whenever.

**Comment by martinklepsch** [comment]
@GetContented please close this, a new Closure library release is underway.
