### ISSUE TITLE
quick start (om.next) -- could not find artifact org.omcljs:om:jar:0.9.0-SNAPSHOT

### ISSUE THREAD

**Issue by eyston** [omcljs/om#385]
Sorry if this is not an appropriate place for this question.

While following the [quick start wiki](https://github.com/omcljs/om/wiki/Quick-Start-%28om.next%29) (or trying out the om next todo example) I am unable to install dependencies for om.next due to the following error:

```
Could not find artifact org.omcljs:om:jar:0.9.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I'm not sure if my environment is screwed up or if I'm just jumping the gun and om.next isn't public yet.  Thanks.

**Comment by shofetim** [comment]
You will need to checkout and build the project locally, it isn't on clojars yet.

**Comment by eyston** [comment]
thanks!

**Comment by adam-r-kowalski** [comment]
I think it might be useful to have this information on the wiki, as people who just follow the tutorial might not be aware of this.

**Comment by drakezhard** [comment]
I agree, although the tutorial isn't even listed in the wiki. I don't think a lot of people will try it until it gets to alpha in a month, and by then it om.next will be on clojars.

**Comment by GetContented** [comment]
Actually @drakezhard , the tutorial *is* listed in the wiki under Om Next: https://github.com/omcljs/om/wiki but it seems a little premature to start filing bug requests about pre-alpha software. Seems more like something for the discussion lists, IRC or some other forum.
