### ISSUE TITLE
when will om next and datomic production ready ?

### ISSUE THREAD

**Issue by rhacker** [omcljs/om#387]
Hi,
I'm very excited about Om Next and the future it holds. A lot of progress has been made and we seem to have a working version of Om next. I'm preparing for a new project. I would like to know when will Om next ready for production and of course with datomic as backend ?

Cheers :+1:

**Comment by swannodette** [comment]
There'll probably be in an alpha in about a month or so.

**Comment by rhacker** [comment]
awesome, thanks for your answer (y)
