### ISSUE TITLE
No *print-fn* error following Quick Start (Om Next) wiki

### ISSUE THREAD

**Issue by mudphone** [omcljs/om#388]
When I visit `http://localhost:3449` for the first time, I get the following error:
````
Uncaught Error: No *print-fn* fn set for evaluation environment
````

I'm assuming that I need to put `(enable-console-print!)` at the top of `src/om-tutorial/core.clj`. When I do that I can see the "Hello world!" message in the console.

You could perhaps add it to the "#Checkpoint" section of the wiki, in the om-tutorial.core snippet.

**Comment by felixflores** [comment]
+1

```clojurescript
(ns om-tutorial.core
  (:require [goog.dom :as gdom]
            [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]))

(enable-console-print!)

(println "Hello world!")
```

**Comment by felixflores** [comment]
**update** I believe this issue is fixed.

**Comment by mudphone** [comment]
Great, that's what I meant.
