### ISSUE TITLE
Om Next - Cache behaves strangely after a while

### ISSUE THREAD

**Issue by bendisposto** [omcljs/om#395]
I am not sure if this is a problem of om or ClojureScript (but I was not able to reproduce it in ClojureScript)

I use the DataScript tutorial as an example. It seems as if the cache stops working properly after the counter has reached 9. 

Reproducing the bug: 
1) Start the app with figwheel (as described in the tutorial) 
2) Click the counter a couple of times (say 4 times) 
3) Select one of the UUIDs from the browser's console  (in my case #uuid "74787b3b-b226-448a-abb5-779c9a9a89b7")
4) (om/from-history reconciler #uuid "74787b3b-b226-448a-abb5-779c9a9a89b7") works as expected
5) Increase the counter to 8, from-history still works
6) Increase the counter to 9, all subsequent from-history calls return nil 

I inspected the index from history using (.-index (:history (:config reconciler))) and the uuid is present, but I cannot retrieve it using get. 
 
    om-datascript.core=> (.-index (:history (:config reconciler)))
    #object [cljs.core.Atom {:val {#uuid "41bee581-d00c-445e-98a0-b24a71637108" #datascript/DB {:schema {}, :datoms [[1 :app/count 7 536870920] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "0955d2eb-8a70-426b-a1ac-459b0a229325" #datascript/DB {:schema {}, :datoms [[1 :app/count 8 536870921] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "71e34a2b-4a9d-4b13-baba-365826ec5589" #datascript/DB {:schema {}, :datoms [[1 :app/count 5 536870918] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "3eca67c2-2943-45aa-855d-4d656804b52c" #datascript/DB {:schema {}, :datoms [[1 :app/count 9 536870922] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "74787b3b-b226-448a-abb5-779c9a9a89b7" #datascript/DB {:schema {}, :datoms [[1 :app/count 11 536870924] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "9418883c-0ebd-434b-892d-467313014d16" #datascript/DB {:schema {}, :datoms [[1 :app/count 10 536870923] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "6c778d04-0233-43cc-a5aa-3d6e9ad8cbe1" #datascript/DB {:schema {}, :datoms [[1 :app/count 6 536870919] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "0b864c2a-bed6-4b55-8a00-dbda860a5c50" #datascript/DB {:schema {}, :datoms [[1 :app/count 12 536870925] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "aa2532d7-5203-4899-b2c1-c403581ea155" #datascript/DB {:schema {}, :datoms [[1 :app/count 3 536870916] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "1666db61-206a-4365-8407-7baeb7c9dc6c" #datascript/DB {:schema {}, :datoms [[1 :app/count 1 536870914] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "db66e8e8-0c01-4503-b301-b7181247a705" #datascript/DB {:schema {}, :datoms [[1 :app/count 2 536870915] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "05d62888-02a7-4d78-8ed7-1577adc8118d" #datascript/DB {:schema {}, :datoms [[1 :app/count 0 536870913] [1 :app/title "Hello, DataScript!" 536870913]]}, #uuid "08ac2845-714a-46ce-8152-0d7083ca3de4" #datascript/DB {:schema {}, :datoms [[1 :app/count 4 536870917] [1 :app/title "Hello, DataScript!" 536870913]]}}}]
    
    om-datascript.core=> (get (.-index (:history (:config reconciler))) #uuid "74787b3b-b226-448a-abb5-779c9a9a89b7")
    nil

**Comment by swannodette** [comment]
We're not taking Om Next feedback until we cut a release. Too many things are changing.
