### ISSUE TITLE
Normalizing, identities, and queries

### ISSUE THREAD

**Issue by Chris-Andrews** [omcljs/om#412]
I have been going over the Om Next tutorials, and I'm wondering if the notion of normalizing applies to queries at all. For an example query:
```
[{:app
  [{:sub1 [{:db/names [{:Mary {:game1 [:points]}}]}]}
   {:sub2
    [{:db/names
      [{:Mary {:game2 [:points]}} {:John {:game2 [:points]}}]}]}
   {:db/names [{:John [:age]}]}]}]
```
Components at any depth in the application state tree may want data from some "root-level" representation, in this case, ```:db/names```. As I understand things, this is a good place to apply ```om/Ident```, so that any reference to ```:db/names``` is regarded as equivalent and any components with overlapping data can change together.

For this query, I believe Om would normalize the ```:db/names``` data into something like:
```
{:db/names
 {:Mary {:game1 {:points 1}, :game2 {:points 2}},
  :John {:game2 {:points 3}, :age 92}}}
```
Does Om have any notion of normalizing the corresponding query, so that you could gather the various pieces to send to the server? In this example:
```
[{:db/names [{:Mary [{:game1 [:points]}
                     {:game2 [:points]}]} 
             {:John [{:game2 [:points]} :age]}]}]
```

**Comment by swannodette** [comment]
There's no need to support this since there are no assumptions about location during parsing. A key can always be served from the root. Everything is up to the discretion of the user writing the parser. You can recursively invoke parse with whatever environment information is needed for context.

**Comment by Chris-Andrews** [comment]
Makes sense, thanks!
