### ISSUE TITLE
[om.next] How to include local development version in project?

### ISSUE THREAD

**Issue by dvcrn** [omcljs/om#413]
With om.next being still alpha, I tried to hack a bit on it. I'm still quite new to clojure and not sure what the optimal workflow for local development is. 

Right now I 
- cloned this project
- changed some things 
- bumped the version to something arbitrary
- `lein install`

Then use the new version inside one project where I want to test it out. Though I am always getting `base.js:1254 Uncaught Error: Undefined nameToPath for om.next.impl.refs` when trying to run it, whereas the current released version works fine.

**Comment by bensu** [comment]
Can you try the same process without the step "changed some things"? We would then now if it's those things that cause the problem. Also do the tests pass after your changes?

**Comment by swannodette** [comment]
Please ask questions like this on Slack #om or IRC #clojurescript. Thanks.

**Comment by dvcrn** [comment]
Whoops, ok!
