### ISSUE TITLE
Join query + params produce error

### ISSUE THREAD

**Issue by anmonteiro** [omcljs/om#417]
OK, so, as minimal as I can make it:

Context: list of things with 3 attributes, just want to query 2 of those, params involved. `'[(:people {:length ?len})]` works as expected (but selects all 3 attrs), `'[({:people [:name :age]} {:length ?len})]` (selecting only name & age) breaks. Code below.

```Clojure
(def app-state
    {:people [{:name "Alice" :age 31 :single false}
              {:name "Bob" :age 25 :single false}
              {:name "Carl" :age 20 :single true}]})

(defn read
  [{:keys [state]} _ {:keys [length]}]
  {:value (take length (:people @state))})

(defui PeopleList
  static om/IQueryParams
  (params [this]
    {:len 3})
  static om/IQuery
  (query [this]
    '[({:people [:name :age]} {:length ?len})])
  Object
  (render [this]
    (apply dom/ul nil
      (map
        #(dom/li nil (str (:name %) ", " (:age %) " years old."))
        (:people (om/props this))))))

  (om/add-root! (om/reconciler {:state app-state
                                :parser (om/parser {:read read})})
                PeopleList
                (gdom/getElement "app"))
```

**Comment by swannodette** [comment]
This is not a bug you must handle normalization yourself. This example works fine for me.

**Comment by anmonteiro** [comment]
Oh well, you literally just fixed it in b5eb1cdfdee27d3f5f21a81335d632cce02e6399, I was getting the error until I upgraded.
Thanks for your time nevertheless!

**Comment by swannodette** [comment]
@anmonteiro ah sorry ok. That was for a different deeper bug. At this early stage it's difficult for me to understand problems which have somewhat misleading titles. Apologies :)

**Comment by anmonteiro** [comment]
My apologies for the title, had no idea how to put it differently as the error only happened when I used the syntax containing a join & params.
