### ISSUE TITLE
getInitialState warning in om.next 1.0.0-alpha2

### ISSUE THREAD

**Issue by Chris-Andrews** [omcljs/om#420]
When creating an Om.Next component with a getInitialState lifecycle method defined, the following warning is issued when the class is instantiated:

>Warning: getInitialState was defined on [Component-Name], a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

Is this the intended Om.Next behavior? I believe React's new preferred method of setting initial state is to define a state value inside an ES6 class constructor, but it seems React is still allowing getInitialState when defined this way, because the value returned by getInitialState is correctly incorporated into the component's state when I run this code.

**Comment by swannodette** [comment]
This is just a bogus warning. Om provides the semantics for `getInitialState` and provides all of the logic to make it work. No way to suppress it and it's just not that important.

**Comment by Chris-Andrews** [comment]
Cool, thank you
