### ISSUE TITLE
Intended behaviour?

### ISSUE THREAD

**Issue by boymaas** [omcljs/om#424]
I was just looking the om.next code and found a section which probably contains unintended behaviour. 

https://github.com/omcljs/om/blob/master/src/main/om/next.cljs#L510

When not supplying options to add-root! it removes the old reconciler attached to a root element, which is intended.

When supplying options is does no attempt to remove old reconcilers or manage a repository of reconcilers. I believe this is unintended behaviour. 

506-508 should move after 511?

**Comment by swannodette** [comment]
Good catch, thanks, fixed https://github.com/omcljs/om/commit/199346ce9c66da9abe5efbeee9cabb1c21ff31e8
