### ISSUE TITLE
Using props with om.next components loses path information

### ISSUE THREAD

**Issue by thheller** [omcljs/om#425]
Working on some tests based on the tutorial [1] I wanted to try refs.

I changed `(list-view one)` to `(list-view {:ref "l1" :list one})` (and ListView accordingly) and noticed that the `(-> this om/path first)` now prints `nil`.

This is due to the path being passed through meta [2] which is only present on `one` not on `props` which is now another map. 

[1] https://github.com/omcljs/om/wiki/Components%2C-Identity-%26-Normalization
[2] https://github.com/omcljs/om/blob/bbd94ac17a4c208f928a84915a050b787b65cb6a/src/main/om/next.cljs#L200

**Comment by thheller** [comment]
Don't want to mix this with #426 but they sort of share the same underlying issue.

Clicking the `+` causes an error `Uncaught Error: No method in multimethod 'om.problem-props/read' for dispatch value: :name`.

```clojure
(defui Person
  static om/Ident
  (ident [this props]
    ;; PROBLEM: props is either person (from query) or {:person person} (from render props)
    (prn [:person/ident props])
    [:person/by-name (or (-> props :name)
                         (-> props :person :name))])
  static om/IQuery
  (query [this]
    '[:name :points :age])
  Object
  (render [this]
    (println "Render Person" (-> this om/props :person :name))
    (let [{:keys [person foo] :as props} (om/props this)
          {:keys [points name foo]} person]
      (dom/li nil
        (dom/label nil (str name ", points: " points))
        (dom/button
          #js {:onClick
               (fn [e]
                 (om/transact! this
                   `[(points/increment ~person)]))}
          "+")
        (dom/button
          #js {:onClick
               (fn [e]
                 (om/transact! this
                   `[(points/decrement ~person)]))}
          "-")))))

(def person
  (om/factory Person
    {:keyfn #(-> % :person :name)}))

(defui ListView
  Object
  (render [this]
    ;; PROBLEM: path is nil
    (prn ["Render ListView" (-> this om/path)])
    (let [list (om/props this)]
      (apply
        dom/ul nil
        (for [item list]
          (person {:person item :foo "bar"}))
        ))))

(def list-view (om/factory ListView))
```

**Comment by thheller** [comment]
Full code at
https://github.com/thheller/shadow-om-next-tests/blob/e370e7d082be58c227b529986de0cad679acbdfe/src/cljs/om/problem_props.cljs

**Comment by swannodette** [comment]
You are passing data that does not match query. Not interested in supporting that.

**Comment by thheller** [comment]
Passing `props` between components is fairly fundamental to React and not being able to use `:ref` seems to be at conflict with the implementation of `om/factory` which clearly seeks to support at least `:ref`.

I'm still learning om.next so it might not be as apparent to me yet why you are not interested in supporting this.

I thought about a solution for a while and all it would take is separating the props from the om-managed data. Effectively changing the `om/factory` generated `fn` to the signature of `(fn [data props & children])` and creating one new accessor for this data similar to `om/props` (eg. `om/data`).

Anyways, I won't bother you any further with this.
