### ISSUE TITLE
React lifecycle semantics not preserved

### ISSUE THREAD

**Issue by grav** [omcljs/om#431]
If I use queries for a component and then update the app state, `componentWillReceiveProps` is called with a nil `next` parameter.

I am currently using `componentDidUpdate` instead, where I do have access to the next props, but at this point I have lost my previous props, meaning I cannot calculate the prop changes.

**Comment by grav** [comment]
Just noticed `componentDidUpdate` should in fact give me prev-props and prev-state, but from my tests, it is in fact giving me the current props and state, making a diff calculation impossible.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/0f4f421e63b1eb93631f33857e01ad3267f0530f
