### ISSUE TITLE
om.next: set-state! does not rerender components when they have a reconciler 

### ISSUE THREAD

**Issue by Jannis** [omcljs/om#432]
I noticed that `update-state!` and `set-state!` do not currently trigger a rerender of om.next components if a reconciler is being used.

At the moment, `set-state!` simply queues a component update via the reconciler if there is one. However, since the reconciler only watches the application state and not the local state of the component, neither `.forceUpdate` nor `update-component!` is ever called and so the component is never rerendered.

A possible fix could be to change

    (if-let [r (get-reconciler component)]
      (p/queue! r [component])
      (.forceUpdate component)))

to

    (when-let [r (get-reconciler component)]
      (p/queue! r [component])
    (.forceUpdate component)))

in `set-state!` to always force updates when the local component state is changed. But my understanding of the internals and what the queue is good for in this case is limited, so there's probably a better way.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/f9bf808e794444ed3a737354a918ee81e5be4781
