### ISSUE TITLE
om.next: set-state! requires the component to have queries

### ISSUE THREAD

**Issue by grav** [omcljs/om#433]
When using `set-state!` and then forcing a re-render by eg. updating the app-state, I get various exceptions. They all seem to come from the fact that I have a reconciler but no queries in my component, which makes Om queue up the component. Here's the last part of `om.next/set-state!`:

```
(if-let [r (get-reconciler component)]
    (p/queue! r [component])
    (.forceUpdate component))
```

I guess a component should only be `queue!`'d up if it has queries?

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/0b9117fd2ffe44795da1e3e737cb921b459a6c67
