### ISSUE TITLE
om-next: Remove :selector inherited from parent AST node from env when parsing (confuses recursive calls)

### ISSUE THREAD

**Issue by awkay** [omcljs/om#434]
When writing a recursive read that uses om/parser, the selector from the parent is passed to read even though the specific AST node being parsed doesn't have one (e.g. it isn't cleared from the environment). This means you have to defensively clear :selector before your recursive call or you cannot detect the difference between a prop and a join in read (since both get a keyword as a key).

An additional nicety might be to pass the AST node type through the environment, and expand the types to include the real type (e.g :join).

**Comment by swannodette** [comment]
This ticket needs rationale. Please start a discussion in IRC or Slack on this one and we can figure what the actually problem is.
