### ISSUE TITLE
HTTP caching support

### ISSUE THREAD

**Issue by swannodette** [omcljs/om#435]
This ticket is much broader than the title suggests, but this will be the first use case.

`{:remote true}` should become something else.

`{:part :remote}`, `{:part :static}`?
`{:target :remote}`, `{:target :static`}?

We should probably support composition via sets?

`{:target #{:remote :static}}`

`:send` parameter to reconciler would need to become a hashmap of functions.

**Comment by davewo** [comment]
+1 for `:target`

**Comment by thos37** [comment]
:push :remote?

**Comment by swannodette** [comment]
@thos37 `:push` is not a great word for this. It's really about where to forward the message.

**Comment by swannodette** [comment]
I looks like we won't need to pick a name for this. Details forthcoming.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/a47ac1e0e23ef1a9a6d98bf281640e9ff95c98b8
