### ISSUE TITLE
[om.next] ReferenceError: ReactDOM is not defined, when trying the Quick Start guide

### ISSUE THREAD

**Issue by marcolisi** [omcljs/om#437]
I tried the quick start tutorial for om.next although I am unable to make it work as I'm getting the error **ReferenceError: ReactDOM is not defined**

I am trying the example under the section: [**Components With Queries & Mutations**](https://github.com/omcljs/om/wiki/Quick-Start-(om.next)#components-with-queries--mutations)

The error indicated is in *next.cljs* at line 973. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/10454875/10702633/f953f74e-7998-11e5-84e3-46c7f976924e.png)

I am using *org.omcljs/om "1.0.0-alpha5"*

Can someone help? Am I missing something?

**Comment by swannodette** [comment]
This just sounds like a dependency problem. Make sure you aren't including any other dependencies or changing anything about the instructions.

**Comment by marcolisi** [comment]
Thank you for the quick response! Super appreciated. And for guiding me in the right direction.

The problem was due to old compiled scripts, so just needed to do a clean. :)
