### ISSUE TITLE
Alpha7: set-state! and update-state! doesn't re-render component

### ISSUE THREAD

**Issue by Skinney** [omcljs/om#439]
State is updated, but render function is never called.

**Comment by swannodette** [comment]
Please do not open issues w/o supply minimal cases. I cannot reproduce this.

**Comment by Skinney** [comment]
This is embarrassing. I made a minimal case (will do that from now on, sorry) and couldn't reproduce the error. Did a clean build in my project and my problems went away. Sorry about the noise.
