### ISSUE TITLE
Consider adding get-ident

### ISSUE THREAD

**Issue by Jannis** [omcljs/om#441]
Would it make sense to add `get-ident`, similar to how we already have `get-params`? The use case I'm thinking of is that components that refer to a particular object (e.g. `[:person/by-name "John"]`) may want to perform transactions against this reference. An example would be a compact list of people and whenever you click on one person, a "view this person's profile" action is performed.

There are of course ways to construct references like `[:person/by-name "John"]` by hand but to ensure consistency, I think something like `(get-ident this)` would be useful.

Here is an idea of what it could look like:

    (defui PersonLink
      static om/Ident
      (ident [this {:keys [name]}]
        [:person/by-name name])
      static om/IQuery
      (query [this]
        [:name])
      Object
      (render [this]
        (let [{:keys [name]} (om/props this)]
          (dom/a {:on-click
                  (fn [e]
                    (let [ref (om/get-ident this)]
                      (om/transact! this `[(app/view-person {:ref ~ref})
                                           :app/active-person])))}
            (str "View " name)))))

In the above example, the implementation of `'app/view-person` would set `:app/active-person` to `ref`. Other components can then read it via a read method that resolves this ref into the data it refers to.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/4bb831eba2411eddb54ba39031962521dba91557
