### ISSUE TITLE
"No queries exist for component path..." when transacting on leaf component in Unions tutorial

### ISSUE THREAD

**Issue by joshfrench** [omcljs/om#442]
I added this mutation to the Queries with Unions tutorial:

```
(defmethod mutate 'dashboard/update
  [{:keys [state]} _ _]
  {:action
   (fn []
     (swap! state assoc-in [:dashboard/post 0 :content] "ohai"))})
```

When transacted on any leaf component (e.g. `Post` instance) it throws `"No queries exist for component path (om-tutorial.core/Dashboard om-tutorial.core/DashboardItem om-tutorial.core/Post)”`. When transacted on an instance of DashboardItem/Dashboard or the reconciler it’s fine.

Bug or my misunderstanding?

**Comment by swannodette** [comment]
I cannot reproduce this. It works fine in alpha7 for me. If you intend to re-open please put together a full example that doesn't work for you. Thanks.

**Comment by joshfrench** [comment]
I was able to reproduce from a [clean repo](https://github.com/joshfrench/om-bug-repro/blob/master/src/om_tutorial/core.cljs#L152-L167) on alpha7 but not alpha8. Thanks for looking into it though!
