### ISSUE TITLE
Cannot read property 'call' of undefined for denormalize

### ISSUE THREAD

**Issue by tvanhens** [omcljs/om#444]
When trying the [test example](https://github.com/omcljs/om/blob/master/src/test/om/next/tests.cljs#L420-L424) of denormalize using `org.omcljs/om-1.0.0-alpha8`:

```clojure
(defui Person
  static om/Ident
  (ident [this {:keys [name]}]
         [:person/by-name name])
  static om/IQuery
  (query [this]
         [:name :points
          {:friend (om/tag [:name] Person)}
          {:friends (om/tag [:name] Person)}
          :foo :baz]))

(let [origin {:name "Susan" :points 5 :friend {:name "Mary"} :friends []}
      p0 (om/normalize Person origin)
      refs (meta p0)]
  (om/denormalize (om/get-query Person) p0 refs))
```

I get the following error:

`#object[TypeError TypeError: Cannot read property 'call' of undefined]`

The values of refs and p0 are shown below:

``` clojure
{:person/by-name {"Mary" {:name "Mary"}}, nil {}} ; refs

{:name "Susan", :points 5, :friend [:person/by-name "Mary"], :friends []} ; p0
```

**Comment by swannodette** [comment]
This issue just doesn't have enough information. The tests pass. Please determine what the difference is or show the problem in a different context if you're going to open an issue.
