### ISSUE TITLE
[om.next] react native compatibility

### ISSUE THREAD

**Issue by dvcrn** [omcljs/om#445]
Not sure if this belongs here but I wanted to track it anyway. 

Currently with the change to react 0.14 and the addition of `ReactDOM`, using react native is a bit difficult as a DOM is required to make this work. 
Previously React and React-Native had a very similar api (for example `React.render` for rendering out components) but with the split to React + ReactDOM, native is no longer a (if you can even call it that:) drop-in replacement for many things.

A lot of the functionality inside ReactDOM is still present in the normal React Native class but that will probably change over time more and more.

Are there plans of adding an abstraction layer on top of ReactDOM / DOM related functions to make this work or does om.next have other plans in mind?

**Comment by swannodette** [comment]
What is there to do beyond parameterizing the hard coded references to `ReactDOM` and allow the user to supply a custom root render call?

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/b4a2c98b8d87afe9fda6176a74580f8a5416fe09
