### ISSUE TITLE
2nd level map will not get pulled.

### ISSUE THREAD

**Issue by ThomasDeutsch** [omcljs/om#448]
given this query: 
```clj
[{:scheduler/selected-items [
    {:scheduler/selected-placement [
        {:placement/selected-booking [:db/id]}]}]}]
```

and a reader
```clj
(defmethod read :scheduler/selected-items [{:keys [state selector]} _ _]
  {:value (or (d/pull @state selector <eid>)
              :no-selection)})
```

will return no result for the last map (:placement/selected-booking).

if a wildcard is used in the last map: 
```clj
[{:scheduler/selected-items [
    {:scheduler/selected-placement [
        {:placement/selected-booking '[*]}]}]}]
```

i am able to get e result for the last map:
```clj
... :placement/selected-booking {:db/id 74 ...}
```

**Comment by swannodette** [comment]
This ticket will get closed if more information is not provided. As it stand it's not clear that this issue has anything to do with Om at all.

**Comment by ThomasDeutsch** [comment]
seems that his is a datascript issue.
