### ISSUE TITLE
Allow (om/get-computed this) as a shortcut for (om/get-computed (om/props this))

### ISSUE THREAD

**Issue by Jannis** [omcljs/om#451]
A lot of use cases for `om/get-computed` will be about extracting the extra properties in the component (e.g. in `render`). To make this less verbose, we could allow `om/get-computed` to take a component as the first parameter. `(om/get-computed (om/props this))` would still be valid, but could also be written as `(om/get-computed this)`.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/3a0df0cbc8b806ad2c34f2d9c380dd39220d012d
