### ISSUE TITLE
getInitialState warning

### ISSUE THREAD

**Issue by antonkozhin** [omcljs/om#452]
I try set local state

```
(defui MyView
  Object
  (getInitialState [this]
                   {:current-time (t/now)})
  (render [this]
          (let [{:keys [current-time]} (om/get-state this)]
            (dom/div nil current-time))))

(def view (om/factory MyView))

(def reconciler
  (om/reconciler
   {:state app-state
    :parser (om/parser {:read read :mutate mutate})}))

(om/add-root! reconciler
              MyView (.getElementById js/document "app"))
```

and see warning:

"Warning: getInitialState was defined on example4$core$MyView, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?"

**Comment by swannodette** [comment]
It's a bogus error. We might do something about it in the future, but it's not a priority at the moment.
