### ISSUE TITLE
Quick Start Refers to protocol as a method

### ISSUE THREAD

**Issue by bnomis** [omcljs/om#455]
In the quick start. This bit:

"Om Next components always declare the data they wish to read. This is done by implementing a simple protocol om.next/IQuery. This method should return a query expression."

Is talking about a protocol then it says "this method". Something like this maybe better:

"Om Next components always declare the data they wish to read. This is done by implementing the query method of the om.next/IQuery protocol. The query method returns a query expression."

Or, for example, re-write the whole thing like this:

"The query method of the om.next/IQuery protocol declares the data the component wishes to read by returning a query expression."

**Comment by swannodette** [comment]
Again we don't use issues for questions.

**Comment by bnomis** [comment]
There was no question. I am pointing out that in the quick start (and in several other docs) a protocol is referred to as a method.
