### ISSUE TITLE
How does state get in to props?

### ISSUE THREAD

**Issue by bnomis** [omcljs/om#456]
From reading the code in the quick start it seems the render method has to read state from props. But I can't find this explicity mentioned anywhere. Something like:

"In your render method you read state from props." 

Also, how does state end up in props? It's added by the reconciler I presume.

Sorry if this is obvious.

Thanks.

**Comment by swannodette** [comment]
Please don't open issues that are questions. You can direct questions to either ClojureScript IRC or Slack.

**Comment by bnomis** [comment]
I phrased the issue as a question. Perhaps it would be better written as: The docs do not explain that state ends up in props or how it gets there.
