### ISSUE TITLE
Disable om.next log

### ISSUE THREAD

**Issue by antonkozhin** [omcljs/om#459]
Can I disable om.next log? I have transaction very often and log is full.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/e789f092150f030f100c80d9140520e7d98eadb5

**Comment by antonkozhin** [comment]
I try
```
(def reconciler
  (om/reconciler
   {:state app-state
    :parser (om/parser {:read read :mutate mutate})
    :logger false}))
```
It isn't working.

**Comment by swannodette** [comment]
Need more information. Are you on the latest alpha?

**Comment by antonkozhin** [comment]
Sorry, I found my mistake. Thank you.
