### ISSUE TITLE
merge-novelty! does not support datascript or other stores

### ISSUE THREAD

**Issue by pleasetrythisathome** [omcljs/om#462]
https://github.com/omcljs/om/blob/master/src/main/om/next.cljs#L1053

In the case of datascript, res can be transacted directly into the db without having to normalize or sift-refs. 

Could you support passing :merge as a config argument to the reconciler?

**Comment by swannodette** [comment]
@pleasetrythisathome the merge bit is easy to do but the more interesting problem is sorting out what keys changed - this is the purpose of `om.next/queue-calls!`, we queue up those keys to narrow the scope of the application parts that need to re-render.

What exactly are you transacting? datoms? Or a tree of entities?

**Comment by pleasetrythisathome** [comment]
@swannodette in the case of :remote calls for reads that can't be satisfied with local data, i'm currently returning a tree of entities resulting from a pull query on datomic. In this case, the read methods in the parser on the server can return a :value vector of reads that should be queued. 

I was playing around today and ended up with this for handling transacting remote reads, as well as still passing changed :value queries to be queued. 

```clojure
(defn transit-post [conn url]
  (fn [{:keys [remote]} cb]
    (.send XhrIo url
      (fn [e]
        (this-as this
                 (let [res (t/read (t/reader :json) (.getResponseText this))
                       [mutations reads] (->> res
                                              (group-by (comp keyword? first))
                                              (mapv (comp (partial into {})
                                                          second)))]
                   (d/transact conn (apply concat (vals reads)))
                   (cb mutations))))
      "POST" (t/write (t/writer :json) remote)
      #js {"Content-Type" "application/transit+json"})))
```

In the instance of the server pushing updates to a client that didn't trigger the mutation (and thus wouldn't be triggering the callback on send, but rather the merge! method or something similar), i could see instances where both datoms or entity trees would make sense. Could normalize all trees of entities down to datoms...

If mutations in the system are always handled in the parser, then i could see being able to compute changed queries for each client. Things get more complicated when there are multiple servers writing to the same db. I suppose I could submit the changed queries to a queue and then have each server responsible for pushing to its connected clients.

Alternatively, it'd be great to be able to just listen to datomic's transaction stream, and send datoms to each client that are scoped by their permissions. But then we're at the problem you mention of determining what changed. Maybe the solution here is querying the transactions to determine changed keys, pushing datoms and keys to clients, and then submitting changes to ```om.next/queue-calls!``` and transacting the datoms, which is essentially what i'm doing above (albeit for a tree of entities).

**Comment by swannodette** [comment]
I've fixed the fundamental problem. Making accommodations for Datomic specific solution are not in scope.

https://github.com/omcljs/om/commit/c901535455c44b5a765a4be8cb45be1c047ae913

**Comment by pleasetrythisathome** [comment]
Makes sense, ```:merge``` function looks like a good solution from here.
