### ISSUE TITLE
Parameterizing join causes "No queries exist..."

### ISSUE THREAD

**Issue by joshfrench** [omcljs/om#466]
Parameterizing an otherwise functional join causes transactions to throw "No queries exist..." even when the params are empty or ignored. I've reproduced on alpha18 but have seen it at least as far back as alpha14.

Here's a repo with a minimal [reproduction](https://github.com/joshfrench/om-params-bug/blob/e8fe46d9269fab28a4f37294576992ddd766bffb/src/om_tutorial/core.cljs). The join in question is on the Dashboard component:

```cljs
static om/IQuery
(query [this]
  ;; `[{:dashboard/posts ~(om/get-query Post)}] ;; works fine
  `[({:dashboard/posts ~(om/get-query Post)} {:foo "bar"})] ;; "No queries exist for component path (om-tutorial.core/Dashboard om-tutorial.core/Post) or data path [:dashboard/items]"
  )
```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/02315e7775900709ae0d77a9dbec63de0600b779
