### ISSUE TITLE
Minor warning in getting started tutorial

### ISSUE THREAD

**Issue by theophilusx** [omcljs/om#467]
This is so minor it may not even be worth mentioning. However, it also seems easy to fix. Given it is probably always good to remove anything which might cause confusion or concern for a new user, I figured best to mention it anyway. 

In the tutorial, you use js/react.render, which causes the following warning in the console

Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

changing to js/ReactDOM.render seems to work fine and gets rid of the warning message

I did say it was minor!

**Comment by swannodette** [comment]
fixed
