### ISSUE TITLE
Uncaught TypeError: Cannot read property 'om$isComponent' of undefined

### ISSUE THREAD

**Issue by antonkozhin** [omcljs/om#471]
The use of set-state! results in an error: Uncaught TypeError: Cannot read property 'om$isComponent' of undefined.
[Sample](https://gist.github.com/antonkozhin/5f421ff17c4b855bf900)

If change
```
(om/add-root! reconciler
              MainView (.getElementById js/document "app"))
```

to 

```
(om/add-root! reconciler
             ClockView (.getElementById js/document "app"))

```

then the error disappears.

**Comment by swannodette** [comment]
fixed in master
