### ISSUE TITLE
"Uncaught ReferenceError: ReactDOM is not defined" as release 1.0.0-alpha11

### ISSUE THREAD

**Issue by marcolisi** [omcljs/om#475]
Getting the JavaScript error `Uncaught ReferenceError: ReactDOM is not defined` for any call to `js/ReactDOM.render` as of [org.omcljs/om "1.0.0-alpha11"]

I recently upgraded my project dependencies to the following, but was getting the above error:

[org.clojure/clojurescript "1.7.170"]
[org.clojure/core.async "0.2.371"]
[org.omcljs/om "1.0.0-alpha21"]
[lein-cljsbuild "1.1.1"]
[lein-figwheel "0.5.0"]

The other dependencies that I did not update:

[ring "1.4.0"]
[ring/ring-defaults "0.1.5"]
[compojure "1.4.0"]
[datascript "0.13.3"]
[sablono "0.3.6"]
[cljsjs/bootstrap "3.3.5-0"]
[com.cemerick/url "0.1.1"]

From prior tests, starting from a point in time that worked. I narrowed the problem to OM. I then backtracked from the latest release `1.0.0-alpha21` up to a release that worked (ensuring to do a `lein clean` in between each test). I ended up on the release `1.0.0-alpha10`, which no longer gave the JavaScript error. Then to ensure that I was getting this behavior, I tested by switching between `1.0.0-alpha11` and `1.0.0-alpha10`, and it consistently gave the error.

I have looked at the commits, just between these two releases, and I have no clue as to why this error would start appearing.

I'm submitting it in case someone else might be getting this error.

Currently, I left it at `1.0.0-alpha10` to keep developing, but it seems to be a problem that is being perpetuated to all following releases (for me anyways).

**Comment by swannodette** [comment]
This likely an environment issue. If you have questions please ask on #om Slack or #clojurescript IRC. No one else has reported this issue.

**Comment by marcolisi** [comment]
Just for reference for anybody else that happens to get this error.

The require statement `[om.dom :as dom]` was never included, and this was causing the dependency to `cljsjs.react-dom` to never be added, thus causing `ReactDOM` to be undefined.

It was an omission on my part as it is stated in the [QuickStart (om.next)](https://github.com/omcljs/om/wiki/Quick-Start-(om.next)). 
As seen in the snippet below:
```clojure
(ns om-tutorial.core
  (:require [goog.dom :as gdom]`
            [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]))
```

Furthermore, the reason why this issue was appearing as of release `1.0.0-alpha11` is due to the commit [remove DOM bits from om.next completely](https://github.com/omcljs/om/commit/af60fa2a7686ff8a4278d52fdf3194d89fd7fd89)

**Comment by narma** [comment]
@marcolisi Thanks! Helps me to resolve same issue in my env.
