### ISSUE TITLE
Migrating with unions destroys app state

### ISSUE THREAD

**Issue by joshfrench** [omcljs/om#479]
Attempting to migrate when query unions are involved nils out my entire app state: `{:dashboard/items [[nil nil] [nil nil]], nil {nil {}}, :om.next/tables #{nil}}`. When I remove unions from the mix, this example works fine; and even when I introduce errors to the non-union version it simply fails to migrate, it doesn't affect my data.

https://gist.github.com/joshfrench/3c83bc0f40348dfd528b

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/520c0e2e496f5aa4b9bb6cc9bd43e3e70dc7d268
