### ISSUE TITLE
process-roots should support processing queries that have no marked roots

### ISSUE THREAD

**Issue by awkay** [omcljs/om#481]
If you call process-roots on a query (or query portion) that has no "moved roots" it returns nothing. It should instead return the unmodified query (and rewrite should then be identity for that portion of the query). That way process-roots and rewrite can be used without having to tease apart which are which.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/ce78741d93bbd406d7d264ffd939d543c52c2406
