### ISSUE TITLE
Process-roots fails on non-rooted queries that contain ...

### ISSUE THREAD

**Issue by awkay** [omcljs/om#489]
Looks like when you pass a recursive query to process roots, but do not mark anything as an alternate root, then it gives a "... not ISeq" error. I've produced a failing test in a devcard on a PR, but can refactor that, shorten it, and move it to test src if you'd like

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/63361fdf53f557f5f718a57293b2b922e343dd16
