### ISSUE TITLE
nil query breaks :or destructoring

### ISSUE THREAD

**Issue by pleasetrythisathome** [omcljs/om#490]
https://github.com/omcljs/om/blob/master/src/main/om/next/impl/parser.cljc#L143-L144

query' is destructured from ast passed into parser when nil. breaks support for :or destructoring in readers such as

```clojure
(defn reader
  [{:keys [query state]
    :or {query '[*]}
    :as env}
   k
   params])
```

this is a regression from alpha-22

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/fcc30b18126a368329aa0ae7353ad02e8135b56a
