### ISSUE TITLE
Union Query Grammer Mismatch

### ISSUE THREAD

**Issue by caleb** [omcljs/om#491]
I am just diving into Om Next and I have a question about the grammer:

```
QueryRoot    := EdnVector(QueryExpr*)
QueryExpr    := EdnKeyword | IdentExpr | ParamExpr | JoinExpr | UnionExpr
IdentExpr    := EdnVector2(Keyword, EdnValue)
ParamExpr    := EdnList2(QueryExpr | EdnSymbol, ParamMapExpr)
ParamMapExpr := EdnMap(Keyword, EdnValue)
JoinExpr     := EdnMap((Keyword | IdentExpr), (QueryRoot | RecurExpr))
RecurExpr    := '...
UnionExpr    := EdnMap(Keyword, QueryRoot)
```

From this it looks like a union expression is a map of keys to vectors (QueryRoots).

In the example of union queries on the wiki this example is given:

```
(in-ns 'om.tutorial.core)
(om/get-query Dashboard)
;; =>
;; [{:dashboard/items
;;   {:dashboard/post    [:id :type :title :author :content :favorites],
;;    :dashboard/photo   [:id :type :title :image :caption :favorites],
;;    :dashboard/graphic [:id :type :title :image :favorites]}}]
```

I had assumed that the `{:dashboard/items {…}}` part of the query was the union query, but it is a map of key to a map.

Is there something I'm missing? Or is one of these pieces of documentation out of date?

**Comment by swannodette** [comment]
Good catch, the grammar is fixed in master now.
