### ISSUE TITLE
set state handling issue

### ISSUE THREAD

**Issue by swannodette** [omcljs/om#494]
```clj
(defui Counter
  Object
  (componentWillMount
    [this]
    (om/set-state! this {:count 0}))
  (componentDidMount
    [this]
    (om/update-state! this update :count inc))
  (componentDidUpdate
    [this _ _]
    (om/update-state! this update :count inc))
  (render
    [this]
    (let [count (om/get-state this :count)]
      (dom/div nil
      (str "COUNT: " count)))))

(def counter (om/factory Counter))
```

This code doesn't currently create an animation loop.

**Comment by swannodette** [comment]
Related `set-query!` doesn't seem to work in `componentWillUpdate` and `transact!` does work in `componentDidUpdate`. Likely all the same issue.

**Comment by den1k** [comment]
Especially if requestAnimationFrame is the desired render frequency, it's questionable whether state should be at the center of the render decision.
@swannodette, what about an optional explicit setting for requestAnimationFrame? Useful for stateless components. Also avoids the only once called state transition fn in `componentDidMount`.

```
(defui MicVolumeIndicator
       Object
       (render
         [this]
         (let [analyzer-node (om/get-computed this :analyzer-node)
               volume (util.audio/get-current-volume analyzer-node)]
           (dom/div nil
                    (str "Volume: " volume)))))

(def mic-volume-indicator (om/factory MicVolumeIndicator
                                      {:render-loop :request-animation-frame}))
```

**Comment by swannodette** [comment]
@den1k we're not going to do that. More sophisticated animation support is downstream concern.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/e8e17761a187b6e7bdf2cb0000744d5daae64c01

**Comment by den1k** [comment]
@swannodette using the `counter` example above under `[org.omcljs/om "1.0.0-alpha25-SNAPSHOT"]` master the counter stops at 3.

**Comment by anmonteiro** [comment]
@den1k be sure to clean your build, working for me

**Comment by den1k** [comment]
@anmonteiro thanks! Did it but looks like intellij cached the deps. Now works!!
