### ISSUE TITLE
db->tree does not tolerate graph loops

### ISSUE THREAD

**Issue by awkay** [omcljs/om#495]
If you use ... in a query against a db that has graph loops you get infinite recursion. Be nice to do something like Datomic and either allow a depth limit or also tracks idents already seen.

**Comment by swannodette** [comment]
One open question - what should we return? Datomic returns `db/id` if the recursion limit is exhausted. idents?

**Comment by awkay** [comment]
I wrote the test as if it returned ident...so that was my thought as well.

**Comment by awkay** [comment]
This also breaks migrate, of course, since it uses this function to follow tempids and fix them.
