### ISSUE TITLE
process-roots drop siblings of re-rooted queries

### ISSUE THREAD

**Issue by awkay** [omcljs/om#503]
If your query contains multiple things:

[:a {:j [{:k [:l :m]}]}]

and one of them gets re-rooted, then the remainder of the items get dropped. Also, mutations are not passed through at all.

**Comment by awkay** [comment]
So there is definitely more thinking to do on this problem, since each item in a query at the root level is a sibling...e.g. the common case is that there are multiple queries at root, almost certainly joined into the root query by made-up keys and all wanting to be re-rooted. If they all want a re-root, the current algorithm actually works OK.

When we do transaction, we also add in mutations. This one is the easy case since mutations are not tree-like...passing them through seems trivial, and I've tried an exploratory version of process roots that does this, and it works just fine.

Another case is where *one or more* of the siblings in the root query does not ask for a re-root. In that case the sibling is lost (the final empty? check to prevent process roots from losing non-modified queries only works if there was a single thing to re-root). This case seems simple enough to handle, and should not really hurt anything...you're just saying that the server understands that particular branch without modification.

One final case that I'm still thinking about is the recursive one where you could possibly end up with siblings at some new root that both need to be kept (e.g. both share the same throw-away prefix)...it would be same as from the start of the algorithm, but no mutations would be there. However, If that happened then you'd need to promote all of the siblings to the top level, which means a query that started out with n rooted branches would end up n+m of them.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/7640db0ac4855b64462610929f9aea09b71926ca
