### ISSUE TITLE
Typos in "Queries With Unions" listing

### ISSUE THREAD

**Issue by Peeja** [omcljs/om#509]
I came across a couple of typos in the [final listing of "Queries With Unions"](https://github.com/omcljs/om/wiki/Queries-With-Unions#putting-it-all-together). I'd fix them myself, but the page says not to do that, so I'll leave them here.

* In `(def Photo …)`, `(dom/p nil "Caption: ")` should (I assume) be `(dom/p nil (str "Caption: " caption))`
* In `(defmethod read :dashboard/items …)`, `(into [] (map #(get-in st %)) (get st k))` should be `(into [] (map #(get-in st %) (get st k))))` (the result of `get` should be an argument of `map`, not an argument of `into`.

**Comment by swannodette** [comment]
The first one is a typo and you can fix that. The second one is not, `into` support transducers.

**Comment by Peeja** [comment]
Oh, of course! I'm still not used to seeing transducers. I'll fix the first one.

(For the future, is this the most useful way to point out issues like this in the tutorials before fixing them?)

**Comment by swannodette** [comment]
@Peeja or ping the community on the #om Slack channel or the #clojurescript IRC channel.
