### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined on queries with unions example

### ISSUE THREAD

**Issue by rhacker** [omcljs/om#524]
Hi @swannodette, I have an error while trying out Queries and Unions example ( https://github.com/omcljs/om/wiki/Queries-With-Unions ).
Ui rendering works correctly but whenever I click on favourite button I got 
The setup ( dependencies ) is the same as yours.
```
Uncaught TypeError: Cannot read property 'call' of undefined
```

Please let me know if I can provide more information.

**Comment by swannodette** [comment]
Please do not open issues about tutorial difficulties without first checking in on the #om Slack channel or #clojurescript IRC channel.

**Comment by rhacker** [comment]
Thanks for pointing out, I will go there instead :)
