### ISSUE TITLE
bug in om.next/process-roots

### ISSUE THREAD

**Issue by noonian** [omcljs/om#526]
Process roots seems like it doesn't preserve union queries correctly.

Assuming nothing in the query is annotated as a `:root-query`, `process-roots` should return the same query given to it in the `:query` key of the returned map (please correct me if this assumption is wrong).

In my application I have this remote query:

```clojure
[{:app/pages
  {:page/home
   [{:user/rooms [:id :roomname]} {:app/rooms [:id :roomname]}]}}]
```

and the `:query` returned by `process-roots` for that query looks like this:

```clojure
[{:app/pages
  [[:page/home
    [{:user/rooms [:id :roomname]} {:app/rooms [:id :roomname]}]]]}]
```

It looks like the join query was turned into a vector of map entries and never converted back into a map.

**Comment by awkay** [comment]
Yeah, in my tests on line 741 in tests I mis-typed the union syntax. If we correct the syntax, those two tests fail as described above.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/91a6e40109c34ceac2aa99593729da9f644b39bc
