### ISSUE TITLE
Returning {:value nil} from a read causes keys to be missing from query results

### ISSUE THREAD

**Issue by Jannis** [omcljs/om#531]
For example, assume the following read function:

```clojure
(defmethod read :foo
  [_ _ _]
  {:value nil})
```

With this, the query `[:foo]` would result in `{}`. The expected result would be `{:foo nil}`.

**A more realistic example**

Read function:

```clojure
(defmethod read :foo
 [{:keys [state]} key _]
 {:value (get @state key)})
```

Parser calls:

```clojure
=> (parser {:state (atom {:foo nil})} [:foo])
{} ;; should be {:foo nil}
=> (parser {:state (atom {:foo :bar})} [:foo])
{:foo :bar} ;; ok
```

**Comment by swannodette** [comment]
I'm curious as to why this behavior matters at all for your application? Are you using `nil` to signal something?

**Comment by Jannis** [comment]
The more I think of it, the less I think it is needed. Let's close this and we can always revisit if necessary.
