### ISSUE TITLE
Callback given to send should retain root query for normalization

### ISSUE THREAD

**Issue by awkay** [omcljs/om#534]
OK, this is a fun bug. If you change the shape of the query with set-query! while a remote interaction is in progress then the callback will end up using this new root query for normalization, which may no longer match the shape of the server response.

Here is a use case:
- A list widget and an edit widget. Routing between the two is done with set-query!, which swaps one widget for the other.
- The list widget has a refresh button, intended to refresh the list
- If you trigger a refresh and switch to edit before the server response has arrived then the list query is no longer part of the UI, and the callback loses the response.

The correct behavior for clear reasoning is that the callback should understand what query was in effect at the time of the call to send, not some later query that has emerged in the UI.

**Comment by swannodette** [comment]
Should be fixed in master https://github.com/omcljs/om/commit/a13913cb8762f4d09ae0fe3d342059ddc3fb630d
