### ISSUE TITLE
Remote Sync Tutorial: Use :onChange, not :onKeyUp

### ISSUE THREAD

**Issue by Peeja** [omcljs/om#535]
I couldn't get text input to work on the autocompleter in the [Remote Synchronization Tutorial](https://github.com/omcljs/om/wiki/Remote-Synchronization-Tutorial#code). Looks like the problem is here:

```clj
(defn search-field [ac query]
  (dom/input
    #js {:key "search-field"
         :value query
         :onKeyUp
         (fn [e]
           (om/set-query! ac
             {:params {:query (.. e -target -value)}}))}))
```

At `onKeyUp`-time (at least, in React's event system), the `input` doesn't yet have the new `value`. Thus, pressing and releasing <kbd>a</kbd> triggers an `onKeyUp` event, and the handler here sets the query to…`""` (which it already was), and that sets the `value` of the `input` back to `""`. Thus, the "a" never appears.

Replacing `:onKeyUp` with `:onChange` solves the problem.

(Happy to make the change myself, but posting here for confirmation and approval first.)

**Comment by swannodette** [comment]
Please do not report tutorial things here. Just as on Slack or IRC.

**Comment by Peeja** [comment]
Sorry, I thought you said this was a good place for that. Will do.
