### ISSUE TITLE
Situation where componentWillReceiveProps is never called.

### ISSUE THREAD

**Issue by ianbjorndilling** [omcljs/om#536]
I'm having an issue calling transact! on a component that is not the root component or reconciler will never call componentWillReceive props. The component is re-rendering so I'm assuming Om is mutating the props object and then calling setState to trigger a re-render behind the scenes. 

Here's a recreation that should reveal the issue:

```clojure
(defn update-child-data!
  [this value]
  (om/transact! this `[(child/update {:newval ~value})]))

(defui Child
  static om/IQuery
  (query [_]
    [:child/data])
  Object
  (componentWillReceiveProps [_ _]
    (println "will receive props"))
  (render [this]
    (let [{:keys [child/data]} (om/props this)]
      (dom/div nil
        (dom/button #js {:onClick #(update-child-data! this "Child Clicked")} "Child Button")
        (dom/p nil (str data))))))

(def child (om/factory Child))

(defui Root
  static om/IQuery
  (query [_]
    [{:parent/data (om/get-query Child)}])
  Object
  (render [this]
    (let [{:keys [parent/data]} (om/props this)]
      (dom/div nil
        (dom/button #js {:onClick #(update-child-data! this "Parent Clicked")} "Parent Button")
        (child data)))))

(defn read
  [{:keys [state]} key _]
  {:value (get @state key)})

(defn mutate
  [{:keys [state]} _ {:keys [newval]}]
  {:action #(swap! state assoc-in [:parent/data :child/data] newval)})

(def reconciler
  (om/reconciler {:state {:parent/data {:child/data "Hello"}}
                  :parser (om/parser {:read read :mutate mutate})}))

(om/add-root! reconciler Root (.getElementById js/document "app-container"))
```

When clicking the parent button, "will receive props" is printed. When clicking the child button it is not.

**Comment by swannodette** [comment]
Do you have a real use case for `componentWillReceiveProps`? It may be we just drop support for it entirely.

**Comment by anmonteiro** [comment]
Not sure if this is a `componentWillReceiveProps` bug. Adding `:child` to list of `transact!` reads successfully triggers the `componentWillReceiveProps` lifecycle function

**Comment by pkpkpk** [comment]
I use componentWillReceiveProps for coordinating animations. please keep if possible

**Comment by anmonteiro** [comment]
@pkpkpk I have the same use case, and I was going to present it to @swannodette, but what I was doing in `componentWillReceiveProps ` I can perfectly do in `componentWillUpdate`. When is it the case that you can't?

**Comment by ianbjorndilling** [comment]
@anmonteiro Yes, adding the `:child/data` read seems to trigger a re-render in the root.

@swannodette I was using `initLocalState` and `componentWillReceiveProps` to store a computed value in component local state for reuse in the other lifecycle methods. I got around this by just passing it in as a computed property in the parent and calling `transact!` in the parent.
