### ISSUE TITLE
Om Next Tutorial Uncaught Error

### ISSUE THREAD

**Issue by gekkoe** [omcljs/om#546]
In the section of the [tutorial](https://github.com/omcljs/om/wiki/Quick-Start-%28om.next%29) titled "Changing Queries Over Time", upon pasting the code into my editor and saving, the Chrome dev console reports the following error:

```javascript
Uncaught Error: No protocol method IMultiFn.-add-method defined for type function: function om_tutorial$core$read(p__29586,key,params){
var map__29590 = p__29586;
var map__29590__$1 = ((((!((map__29590 == null)))?((((map__29590.cljs$lang$protocol_mask$partition0$ & (64))) || (map__29590.cljs$core$ISeq$))?true:false):false))?cljs.core.apply.call(null,cljs.core.hash_map,map__29590):map__29590);
var env = map__29590__$1;
var state = cljs.core.get.call(null,map__29590__$1,new cljs.core.Keyword(null,"state","state",-1988618099));
var st = cljs.core.deref.call(null,state);
var temp__4423__auto__ = cljs.core.find.call(null,st,key);
if(cljs.core.truth_(temp__4423__auto__)){
var vec__29592 = temp__4423__auto__;
var _ = cljs.core.nth.call(null,vec__29592,(0),null);
var value = cljs.core.nth.call(null,vec__29592,(1),null);
return new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"value","value",305978217),value], null);
} else {
return new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"value","value",305978217),new cljs.core.Keyword(null,"not-found","not-found",-629079980)], null);
}
}cljs$core$missing_protocol @ core.cljs:261cljs$core$_add_method @ core.cljs:9596(anonymous function) @ core.cljs:6
utils.cljs:38
```

**Comment by tedfoye** [comment]
gekkoe,

Removing `:scope test` from the `figwheel-sidecar` dependecy in `project.clj` should allow the code in `Changing Queries Over Time` to run.

Ted

**Comment by awkay** [comment]
Hey Ted, 
Thanks for the catch...I'll fix the dependencies.

**Comment by gekkoe** [comment]
@tedfoye This doesn't seem to have fixed it. I still get an uncaught error after getting rid of :scope test and restarting the REPL.

That said, I found it interesting that if I just start the REPL up with the code from "Changing Queries Over Time" in place, I get no error. However if I then remove the code in core.cljs, paste in the code from the prior section "Components With Queries & Mutations", save, then undo so that the "Changing Queries Over Time" code is back in place and re-save, the error throws again.

So I'm assuming at this point to reproduce this error you need to have been following along from the prior state of the code. I haven't attempted to analyze it any deeper to understand why that might be though, as I"m not at all familiar with the inner workings of Clojurescript yet.

**Comment by swannodette** [comment]
Please do not open tickets about tutorials. Get help in Slack or IRC channels.

**Comment by gekkoe** [comment]
@swannodette I didn't actually need help, as I got things working despite the error. I'd just thought the authors might want to fix the problem so as not to confuse other users.

My apology. I hadn't realized there was a different preferred method of error handling for this portion of the repo.

**Comment by Bost** [comment]
I bumped to the same error and I'm quite glad this (unwanted) ticket exists. It helped! Thanks & sorry for contradicting.

**Comment by dylanrevisited** [comment]
For anyone still having this problem the solution is simple, just run (clean-builds) in the REPL

`cljs.user=> (clean-builds)`

**Comment by ashnur** [comment]
@dylanrevisited what if you don't have a repl?
