### ISSUE TITLE
`query->ast` loses info

### ISSUE THREAD

**Issue by awkay** [omcljs/om#549]
I'm doing AST transforms, and the transforms lose data like `:component` and `:query-root`, which means the sequence:

```
(query->ast ...)
(transform ast)
(ast->query ast')
```

is no longer usable with things like `tree->db` since `:component` is needed for normalization.

I would expect  `(comp ast->query query->ast)` to be isomorphic to `identity`.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/b16583be8f50ec17ed100ad4880f75532826273b
