### ISSUE TITLE
Parameterized root queries will not trigger renders

### ISSUE THREAD

**Issue by awkay** [omcljs/om#554]
It looks like if a parameterized query gives back the following response:

`{ (:prop {:x 1})  value }`

then the parameterized property gets queued for re-render. The `reconcile` stop tries to look up the components by key, but this key `(:prop {:x 1})` won't be found, causing no render to happen for `:prop`

NOTE: I am reporting this after reading the source in the context of someone else's problem. I do not personally have a verified failing case.

**Comment by swannodette** [comment]
This is not a valid query.

**Comment by awkay** [comment]
You are right, it is a response (as I said in the description). I assumed you could figure out the query for yourself.

**Comment by maackle** [comment]
@swannodette, I believe I created a test case that illustrates what @awkay mentioned: https://gist.github.com/maackle/136dd47e133571d89483. On lines 37 and 40 are two alternative queries; one works, one doesn't.

A complete lein project for it is [here](https://github.com/maackle/om-next-sandbox/blob/parameterized-root-query-bug/src/om_sandbox/cards/root_query_bug.cljs)

**Comment by fehrenbach** [comment]
Is this confirmed? How do people work around it?

**Comment by anmonteiro** [comment]
this is a non-issue. the query in @maackle 's gist is wrong, so it should not be expected to work

**Comment by maackle** [comment]
What is wrong about a parameterized root query? This is the query, for reference:

```clj
'[{(:message {:size ?size}) [:text]}]
```

**Comment by swannodette** [comment]
@maackle that's an invalid query, refer to the grammar in `om.next.parser`

**Comment by swannodette** [comment]
Please do not comment on this issue anymore. Thanks.
