### ISSUE TITLE
Make db->tree tolerate ParamExpr

### ISSUE THREAD

**Issue by olivergeorge** [omcljs/om#558]
Currently db->tree doesn't handle queries which include ParamExpr.

It would be useful to strip these out in the case where a remote has processed the ParamExpr and the client simply needs to access the data.

Something like the code below might be suitable.  

```clj
(defn param-expr?
  "Returns true if x is param expr."
  [x]
  (and (list? x)
       (== 2 (count x))
       (map (nth x 1))))

(defn db->tree
...
       (if (= '[*] query)
         data
         (let [query (mapv #(if (param-expr? %) (first %) %) query)
               {props false joins true} (group-by #(or (join? %) (ident? %)) query)]
```

One thing I haven't worked out is whether it's necessary to handle QueryExpr and EdnSymbol cases separately.

```
ParamExpr    := EdnList2(QueryExpr | EdnSymbol, ParamMapExpr)
```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/c588189805e0dfd468000f4e7cb7476074146787
