### ISSUE TITLE
Om's data structures should be compatible with core.reducers

### ISSUE THREAD

**Issue by drusellers** [omcljs/om#564]
While working with Specter I ran into an issue where the OM data structure did not implement the core.reducers protocol. The full error conversation is here https://github.com/nathanmarz/specter/issues/46#issuecomment-168837093

The the class in question was [IndexedCursor](https://github.com/omcljs/om/blob/master/src/main/om/core.cljs#L652)

My specific dependencies are

```
  :dependencies [[com.rpl/specter "0.9.0"]
                 [org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.170"]
                 [cljsjs/react "0.14.3-0"]
                 [cljsjs/react-dom "0.14.3-1"]
                 [cljsjs/react-dom-server "0.14.3-0"]
                 [org.omcljs/om "0.9.0"]
                 [sablono "0.5.3"]]
```

**Comment by swannodette** [comment]
Not interested in supporting reducers anymore - use transducers instead. If you want/need to support reducers you can implement the protocol yourself.

**Comment by drusellers** [comment]
Thank you for the feedback. I will relay back to the Specter project.
