### ISSUE TITLE
Om Tempid Predicate

### ISSUE THREAD

**Issue by egracer** [omcljs/om#567]
Considering that `TempId` has a different implementation in Clojure and ClojureScript, it'd be helpful for there to be one standardized predicate in `om.tempid` for checking if some data is a `TempId`.

E.g.:

```
(defn is-om-tempid? [val]
    #?(:clj (instance? TempId val)
       :cljs (= TempId (type val))))
```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/1a834e750a83e8e25f77f5128374873fb7d22112
