### ISSUE TITLE
Permanently Blank Input In Remote Synchronization Example

### ISSUE THREAD

**Issue by seako** [omcljs/om#580]
In the autocompleter portion of the remote synchronization om.next example, the value of the input doesn't change when the user types. This is because the value of the input was configured to be the value of the query from the parent component (which is set to ""). Not setting the value of the input explicitly makes this problem go away.

Since the value of `query` from the AutoCompleter component is not used it can be removed from the list of args.

current code
```clojurescript
(defn search-field [ac query]
  (dom/input
    #js {:key "search-field"
         :value query
         :onKeyUp
         (fn [e]
           (om/set-query! ac
             {:params {:query (.. e -target -value)}}))}))

(defui AutoCompleter
  static om/IQueryParams
  (params [_]
    {:query ""})
  static om/IQuery
  (query [_]
    '[(:search/results {:query ?query})])
  Object
  (render [this]
    (let [{:keys [search/results]} (om/props this)]
      (dom/div nil
        (dom/h2 nil "Autocompleter")
        (cond->
          [(search-field this (:query (om/get-params this)))]
          (not (empty? results)) (conj (result-list results)))))))
```

proposed code
```clojurescript
(defn search-field [ac]
  (dom/input
    #js {:key "search-field"
         :onKeyUp
         (fn [e]
           (om/set-query! ac
             {:params {:query (.. e -target -value)}}))}))

(defui AutoCompleter
  static om/IQueryParams
  (params [_]
    {:query ""})
  static om/IQuery
  (query [_]
    '[(:search/results {:query ?query})])
  Object
  (render [this]
    (let [{:keys [search/results]} (om/props this)]
      (dom/div nil
        (dom/h2 nil "Autocompleter")
        (cond->
            [(search-field this)]
          (not (empty? results)) (conj (result-list results)))))))
```

**Comment by swannodette** [comment]
Please do not open issues about the tutorials. Ask for help on the #clojurescript IRC channel or the #om Slack channel.

**Comment by seako** [comment]
My apologies, I wasn't sure where this should be directed. I'll definitely direct any future questions to those venues. I think it would be helpful to include a note at the top of the tutorials that if someone is having trouble with a tutorial or believes they have found an issue to post about it in the irc or slack channels.
