### ISSUE TITLE
using existing react component ? 

### ISSUE THREAD

**Issue by mydearxym** [omcljs/om#587]
om is amazing!

Before i dive into , i just wonder if i can use [those react component](https://react.parts/web) in om project ?

**Comment by futuro** [comment]
Use `(js/React.createElement)` (or it's idiomatic counterpart `(.createElement js/React )`) and the component constructor.

So something like the following from [React Day Picker](http://www.gpbl.org/react-day-picker/examples/#simple)

```jsx
export default function SimpleCalendar() {
  return <DayPicker onDayClick={ (e, day) => alert(day) } />;
}
```
becomes
```clojure
(defn create-calendar []
  (let [options {:onDayClick (fn [e day] (js/alert day))}]
    (js/React.createElement js/DayPicker (clj->js options))))
```

**Comment by swannodette** [comment]
Please don't use issues to ask questions. Goto #clojurescript Freenode IRC or the #om Slack channel. Thanks.
