### ISSUE TITLE
`react-key` not working with Om.Next components

### ISSUE THREAD

**Issue by nblumoe** [omcljs/om#592]
I would expect `react-key` to return the `key` when I pass it an Om.Next component.

However, the following implementation does not retrieve that from the component
https://github.com/omcljs/om/blob/6e2c6ba3efe2e3cabfee8d6d49112e30be7afdf3/src/main/om/next.cljs#L461

The implementation does not match the actual data structure, there is no `key` in the props.
Or am I just passing the wrong thing as the argument? Is this not supposed to work on Om.Next component instances?

**Comment by anmonteiro** [comment]
This is happening because React's `key` and `ref` are not in `props` since React v0.12 (see [this React blog post](http://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#breaking-change-key-and-ref-removed-from-this.props)).

I'll work on submitting a patch that addresses this issue.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/ae4c8c0729ca90796364ef21032e89f58d716c0e
