### ISSUE TITLE
focus->path and paths with identity -- expected behavior?

### ISSUE THREAD

**Issue by eyston** [omcljs/om#605]
Hello, I have the following query:

```cljs
[{[:person/by-id 2] [:id :name]}
 {[:person/by-id 5] [:id :name]}]
```

When I focused it by `[[:person/by-id 2]]` I get the following focused query:

```cljs
[{[:person/by-id 2] [:id :name]}]
```

If I call `focus->path` on this query, it gives a focused path of `[:person/by-id]`.  I expected `[[:person/by-id 2]]`.  I'm not sure if my expectation is correct.

This is causing a problem in that child components of the query fail on `full-query` as it can't connect the `focus->path` with the components path.

My understanding is that joined idents are legal parts of `QueryExpr` so this should work.

The code in question is:

https://github.com/omcljs/om/blob/1e51c4812cb9e8dd259a1f6f038a1a725906a74e/src/main/om/next.cljs#L202

```cljs
(let [[k focus'] (join-entry (first focus))
       k (if (ident? k) (first k) k)
       focus'     (if (recursion? focus')
```

https://github.com/omcljs/om/blob/1e51c4812cb9e8dd259a1f6f038a1a725906a74e/src/main/om/next.cljs#L1119

```cljs
(let [q (first (filter #(= path' (-> % zip/root (focus->path path'))) qs))]
  (if-not (nil? q)
```

I guess I expect the behavior similar to `db->tree`:

https://github.com/omcljs/om/blob/1e51c4812cb9e8dd259a1f6f038a1a725906a74e/src/main/om/next.cljs#L1294-L1297

```cljs
(if (ident? key)
  (if (= '_ (second key))
    (get refs (first key))
    (get-in refs (map-ident key)))
```
The use case for this is having a route like `/person/{person-id}` where we are doing root queries directly on a user, e.g. `[[person/by-id ?person-id]]`.

Thanks!

**Comment by swannodette** [comment]
Will need to think about this. It's definitely not a priority for me to make this work.

**Comment by eyston** [comment]
Is the preferred style for `by-id` root queries to use parameters?

```clj
[({get-user (om/get-query UserDetails)} {:id ?id})]
```

vs

```clj
[{[user/by-id ?id] (om/get-query UserDetails)}]
```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/8cf520a425afbc31ae8b7d79289addbfaa68c86e
