### ISSUE TITLE
Warning: Unknown.getDOMNode(...) is deprecated.

### ISSUE THREAD

**Issue by viebel** [omcljs/om#607]
A warning is emitted in the browser console when using latest `om` and `react-with-addons` versions.

```clojure
 [org.omcljs/om "1.0.0-alpha30" :exclusions [cljsjs/react]]
 [cljsjs/react-with-addons "0.14.3-0"]
```

This is the warning:
```
Warning: Unknown.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.
```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/f5a0007d7632f3d5f09ca8f92499a257e3f09cfd
