### ISSUE TITLE
Om Next -- why is IQueryParams separated from IQuery?

### ISSUE THREAD

**Issue by ccorcos** [omcljs/om#608]
Is there any particular reason these are different functions? It seems like we ought to be able to inject the parameters directly into the query function.

One reason I ask this is because I'm not sure when its appropriate. For example, suppose I have a user profile page. Should I use a param?

```clojure
(defui Profile
  static om/IQueryParams
  (params [this]
    {:id (get (om/props this) :user/id)})
  static om/IQuery
  (query [this]
    [(:profile {:id ?id})])
```

Or should I put it right in the query because maybe it doesnt change....

```clojure
(defui Profile
  static om/IQueryParams
  (params [this]
    {:id })
  static om/IQuery
  (query [this]
    [(:profile {:id (get (om/props this) :user/id)))])
```

**Comment by swannodette** [comment]
Please do not use issues to ask questions. Ask questions on #clojurescript freenode IRC or #om Clojurians Slack.
