### ISSUE TITLE
display-name not working

### ISSUE THREAD

**Issue by bago2k4** [omcljs/om#610]
I'm trying to get the component's display-name to work.
Here is an example:
```clojure
(defn simple-component [data owner]
  (reify

    om/IDisplayName
    (display-name [_]
      "simple-component")

    om/IRenderState
    (render-state [_ _]
      (dom/li nil (:name data)))))
```
The problem is that when I open the React tab in Chrome developer tools i see all the components with name _No display name_.
Any suggestion?

**Comment by swannodette** [comment]
Please do not use issue to ask trouble shooting questions. Ask on #clojurescript Freenode IRC or #om Clojurians Slack. Thanks.

**Comment by bago2k4** [comment]
@swannodette i asked here because i thought it was an Om bug but from your reply i sense that it's not.. Documentation doesn't help.
I'll use the Slack channel.

**Comment by raphaelboukara** [comment]
@bago2k4 did you find a solution to this problem?

**Comment by bago2k4** [comment]
@raphaelboukara nope, i tried asking in the Om channel of the Clojure slack organization as @swannodette suggested but no luck, no responses..
