### ISSUE TITLE
[om.next] [tutorial] non-editable autocomplete input in Remote Synchronization Tutorial

### ISSUE THREAD

**Issue by euccastro** [omcljs/om#611]
In the [Building a Simple Auto-completion Widget](https://github.com/omcljs/om/wiki/Remote-Synchronization-Tutorial#building-a-simple-auto-completion-widget) example of the Remote Synchronization Tutorial, the user can't enter any text.  The input field stays blank no matter what.

The fix is to just change the `:onKeyUp` keyword in `search-field` to `:onChange`.

See also:

http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by swannodette** [comment]
Anyone can fix the tutorials.

**Comment by samwich** [comment]
I changed the tutorial to use `:onKeyUp` and clojurescript 1.7.228.

**Comment by euccastro** [comment]
@swannodette: at the top of the tutorial:

> DO NOT EDIT THIS PAGE: This page is under heavy active development.
