### ISSUE TITLE
set-query on root component with :query and :param just work for the 1st time.

### ISSUE THREAD

**Issue by geraldodev** [omcljs/om#617]
The second time it triggers render with the right query param but right away it triggers another two render with :query and :param nil.

See attached minimal case.
[setquery.zip](https://github.com/omcljs/om/files/131047/setquery.zip)

**Comment by anmonteiro** [comment]
this is not a bug.. you must provide a query if you implement `query`.

`(query [this])` is not valid.

**Comment by geraldodev** [comment]
@anmonteiro thank you.

I've bitten by this before.
What I think is confusing is:

If don' need a query on the initial render. I must declare with a valid query, and a read multimethod.
om/IQuery
(query [this] [:foo])

Because this is achieving two things. The initial query and the protocol tag.

I know I've bitten by this before. After spending the amount of time I did expect to remember next time.

Regards,
Geraldo
