### ISSUE TITLE
Changed parameter of nested query not being updated on root node that references it

### ISSUE THREAD

**Issue by geraldodev** [omcljs/om#619]
Hi,

I've trying to implement pagination and I think I've found a very hard to catch issue:

When changing a parameter of a nested query, the fact that its not being updated on root node that references it or even the class-path->query is working fine surprisingly, aside from the fact that is hard to debug the state by just looking at root queries. When you pair the parameter change with another read, like (om/transact '[(app/next-page) :grid)]  two reads are generated to the server. One with the right value and another with the old initial bounded root parameter value.

Please see attached minimal case, with further instructions.
[nestedqueryparam.zip](https://github.com/omcljs/om/files/134426/nestedqueryparam.zip)

Regards,
Geraldo

**Comment by swannodette** [comment]
Please do not open issues like this without first discussing them in Slack.

**Comment by geraldodev** [comment]
Sorry,

That's news, because it has a sound minimal case.
Last one, mr. @anmonteiro checked and I right away closed the issue.

Sorry to bother,
Geraldo
