### ISSUE TITLE
`prop->classes` indexes inconsistent for links and idents

### ISSUE THREAD

**Issue by anmonteiro** [omcljs/om#620]
```clojure
[[:users/by-id 2]]
;; #{:users/by-id} ;; Incorrect, should be the ident

[{[:users/by-id 2] [:id :name :age]}]
;; #{[:users/by-id 2] :id :name :age} ;; Correct

[{[:current-user _]} [:name]]
;; #{[:current-user _] :name} ;; Incorrect, should be #{:current-user :name}

[[:current-user _]]
;; #{:current-user} ;; Correct
```

**Comment by tawus** [comment]
Original Message                                                                                                                                                                                                                                                                                                                                                                                                                                      From: António Nuno MonteiroSent: Wednesday 17 February 2016 19:47To: omcljs/omReply To: omcljs/omSubject: [om] `prop->classes` indexes inconsistent for links and idents (#620)[[:users/by-id 2]]
;; #{:users/by-id} ;; Incorrect, should be the ident

[{[:users/by-id 2] [:id :name :age]}]
;; #{[:users/by-id 2] :id :name :age} ;; Correct

[{[:current-user _]} [:name]]
;; #{[:current-user _] :name} ;; Incorrect, should be #{:current-user :name}

[[:current-user _]]
;; #{:current-user} ;; Correct

—Reply to this email directly or view it on GitHub.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/6795510d7b48bb065d40c683d15af32a0b382278
