### ISSUE TITLE
Is the state data tree must match the ui tree?

### ISSUE THREAD

**Issue by DogLooksGood** [omcljs/om#624]
It's seems to be silly question,  but I'm confusing for how to determine which component should reify `IQuery`.

If I have a UI tree like this:
```
Main                 Root component
  |- Nav               Require for the user informations: user-nick-name
  |- Container          No data required
      |- ContactList     Require for the ContactList
         |- Contact        Require first-name and last-name of each contact
         |- Contact
```

Then, What's the `query` of `Main` and `Container`?

**Comment by swannodette** [comment]
Do not use issues to ask questions. Ask questions in the Clojurians #om Slack channel or #clojurescript irc.freenode.net. Thanks.
