### ISSUE TITLE
index-root fails on links (regression as of OM-612, I think)

### ISSUE THREAD

**Issue by awkay** [omcljs/om#639]
Here is the failing test:

```
(defui LinkedItem
  static om/IQuery
  (query [this] [:a]))

(defui RootWithLinks
  static om/IQuery
  (query [this] [{[:a '_] (om/get-query LinkedItem)}]))

(deftest test-index-queries-with-links
  (let [idx (om/indexer)]
    (is (contains? (p/index-root idx RootWithLinks) :class->components))))
```

Trying to index that simple query causes a failure due to trying to call nil as a function.

Added a nil check to line 108 of next.cljs (query-template) fixes it, but not sure that is the right patch.

**Comment by awkay** [comment]
I put this test and patch on my fork: https://github.com/awkay/om/tree/nil-link

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/7bb51c4230e418ded24157b6cc13766e2147509b
