### ISSUE TITLE
Children don't re-render

### ISSUE THREAD

**Issue by r0man** [omcljs/om#644]
Hello,

I think I found a regression in `1.0.0-alpha31` with `om/children`. Components that use `om/children` don't re-render the children anymore when the underlying data changes.

Here is a minimal example that demonstrates this issue:

```
(ns om-tutorial.core
  (:require [goog.dom :as gdom]
            [om.next :as om :refer-macros [defui]]
            [om.dom :as dom]))

(enable-console-print!)

(def app-state (atom {:children []}))

(defn read [{:keys [state] :as env} key params]
  (let [st @state]
    (if-let [[_ value] (find st key)]
      {:value value}
      {:value :not-found})))

(defn mutate [{:keys [state] :as env} key params]
  (if (= 'load key)
    {:value {:keys [:count]}
     :action #(swap! state update-in [:children] conj (rand-int 10))}
    {:value :not-found}))

(defui Page
  Object
  (render [this]
    (dom/div nil (om/children this))))

(def page (om/factory Page))

(defui Counter
  static om/IQuery
  (query [this]
    [:children])
  Object
  (render [this]
    (let [{:keys [children]} (om/props this)]
      (page
       nil
       (dom/button
        #js {:onClick (fn [e] (om/transact! this '[(load)]))}
        "Load children")
       (dom/ul nil (map #(dom/li nil %) children))))))

(def reconciler
  (om/reconciler
   {:state app-state
    :parser (om/parser {:read read :mutate mutate})}))

(om/add-root! reconciler Counter (gdom/getElement "app"))
```
When pressing the button new child elements are added to `app-state`, but they don't render. This used to work with `1.0.0-alpha30`. Or am I doing anything wrong?

Roman

**Comment by anmonteiro** [comment]
This happens because the underlying props of `Page` (which are always nil) don't change, so `shouldComponentUpdate` returns false and the component doesn't re-render.

There are two possible solutions:

- implement `shouldComponentUpdate` in `Page`
- pass something like `{:key (hash children)}` as the props of `Page`. Since the hash will change whenever the vector of children changes, `Page` will re-render.

**Comment by r0man** [comment]
@anmonteiro I think I understand. I did something similar as you suggested in your 2nd solution, but that felt a bit wrong to me, since now I always have to remember to potentially change the props whenever I change something in the children. 

I'm curious about your 1st solution. Is there a way to get at the next children within the `shouldComponentUpdate` function, so I could try to figure out myself if the children did change? 

Also wouldn't it make sense for om.next to do this by default, if possible? How did om.next know about this in the previous alpha version?

Is this still an issue, or should I close it?

Thanks, Roman.

**Comment by anmonteiro** [comment]
> Is there a way to get at the next children within the shouldComponentUpdate function?

this should work:

```clojure
(shouldComponentUpdate [this next-props next-state]
    (not= (.. this -props -children)
      (. next-props -children)))
```

> How did om.next know about this in the previous alpha version?

It didn't, it worked because `shouldComponentUpdate` was broken; that has been solved in [this PR](https://github.com/omcljs/om/pull/602). Perhaps `shouldComponentUpdate` could figure out if `children` have changed. I'll get back to you on that.

**Comment by r0man** [comment]
@anmonteiro  Cool, this works perfectly! :) I think this should be the default behaviour. Thanks!

**Comment by anmonteiro** [comment]
React also re-renders when `children` have changed, I'm working on a patch that mimics this behavior in Om Next

**Comment by swannodette** [comment]
@anmonteiro great, thanks - we should definitely follow React here.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/ee0fb19c4b32c1bf4a7b10f2644e8adf681f8d12
