### ISSUE TITLE
reconciler's send function not called for subqueries

### ISSUE THREAD

**Issue by cascadian** [omcljs/om#647]
When returning `:remote true` from a read function for a prop or join that is not a direct child of the root query, the reconciler's send function is never called. Is that expected? 

``` clojure
(defmethod read :app/msg
  [env k params]
  {:value :loading
   :remote true})

(defui Home
  static om/IQuery
  (query [this]
    '[:app/msg])
  Object
  (render [this] ...))

(defui AppRoot
  static om/IQueryParams
  (params [this]
    {:route-query (om/get-query Home)})
static om/IQuery
  (query [this]
       '[{:route ?route-query}])
Object
  (render [this] ...))
```

**Comment by bostonou** [comment]
@cascadian Do you have a `read` method for the `:route` key anywhere? I don't think your `read :app/msg` is getting called. What does `(om/props this)` give you in your `AppRoot` `render` function?

**Comment by cascadian** [comment]
yes, the `read` method for the `:route` key does a recursive read.

``` clojure
(defmethod read :route
[{:keys [parser query] :as env} _ _]
  {:value (parser env query)})
```

**Comment by anmonteiro** [comment]
If you're doing recursive parsing you need to return the `:remote` key at the top level.

[Here's](https://github.com/awkay/om-tutorial/blob/master/src/main/om_tutorial/parsing.cljs#L191) an example.

This is a non-issue.

**Comment by cascadian** [comment]
thanks for the example!
