### ISSUE TITLE
"No queries exist for component path"

### ISSUE THREAD

**Issue by lsdafjklsd** [omcljs/om#658]
I've run into this issue with two of my toy projects, on versions alpha22 and the latest. The problem happens when I want to set the `:selected` value in state to the `ref` of the thing that was clicked. After the mutation runs and successfully updates state, something happens and I can't for the life of me figure out what the issue is.

I've created the simplest app possible to reproduce the error here: https://gist.github.com/lsdafjklsd/1c066f38e90ab4ea0e43

When you click an item in the number list, you'll get an error.

Here's what the state atom looks like after the mutation runs:

```clojure
{:numbers/selected [:number/by-id 1],
 :numbers/list
 [[:number/by-id 1]
  [:number/by-id 5]
  [:number/by-id 8]
  [:number/by-id 9]],
 :number/by-id
 {1 {:id 1, :name "one"},
  5 {:id 5, :name "five"},
  8 {:id 8, :name "eight"}, 
  9 {:id 9, :name "nine"}}}
```
And a screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/819451/13896450/f05ecae6-ed61-11e5-9139-5dfa7ab296bd.png)

I apologize if this is totally not the space for this question, but appreciate any help in advance.

**Comment by IwanKaramazow** [comment]
Can't reproduce the problem on the latest alpha. Aside from the fact you forgot `STATIC om/Ident` & `STATIC om/IQuery`, everything seems to work properly.

**Comment by lsdafjklsd** [comment]
Interesting, I'm assuming the latest is `alpha31` I've pushed the repo here https://github.com/lsdafjklsd/my-omnext-issue. What version of Clojurescript are you running?

**Comment by IwanKaramazow** [comment]
I cloned your repo and submitted a pull request which makes `om/Ident` & `om/IQuery` static. Aside from that, everything runs just fine. 

Don't think there's any problem with Om here.

**Comment by lsdafjklsd** [comment]
Yes, and I've fixed the issue in one of the other projects. Thanks for your help!
