### ISSUE TITLE
QueryParams does not work with syntax-quoting and unqualified params

### ISSUE THREAD

**Issue by rpreissel** [omcljs/om#661]
Given the following simple component: 
(See syntax quoting within IQuery - I know that syntax quoting isn't required in this example)

    (defui TestPage
      static om/IQueryParams
      (params [_]
        {:para1 "PARA1"})
      static om/IQuery
      (query [this]
        `[(:query {:para1 ?para1})]))

Try to get the query:

    (om/get-query TestPage)

Results in:

    [(:query {:para1 om-example-app.core/?para1})]

Change the component to use normal quoting:

    (defui TestPage
      static om/IQueryParams
      (params [_]
        {:para1 "PARA1"})
      static om/IQuery
      (query [this]
        '[(:query {:para1 ?para1})]))

Use the same command to get the query, results in:

    [(:query {:para1 "PARA1"})]

The error is in function `var?`:

    (defn- var? [x]
      (and (symbol? x)
           (gstring/startsWith (str x) "?")))

**Comment by anmonteiro** [comment]
This is a non-issue. Use `~'?param` inside syntax quoting.

**Comment by rpreissel** [comment]
Thanks for the fast response. 
I know how to get around this error. But would it not be better to handle unqualified params in a proper way or to warn the user. 
It took me a while to find the reason why my query wasn't working correctly and maybe others too.

From my point of view the changes are only minimal.

    (defn- var? [x]
      (and (symbol? x)
           (or (gstring/startsWith (str x) "?")
               (gstring/startsWith (name x) "?"))))

    (defn- var->keyword [x]
      (keyword
        (if (gstring/startsWith (str x) "?")
          (.substring (str x) 1)
          (.substring (name x) 1))))
