### ISSUE TITLE
Query/Param location in reconciler

### ISSUE THREAD

**Issue by taylorSando** [omcljs/om#668]
Currently the :om.next/queries is being stored in [:config :state :om.next/queries], which is the application state.  I think it should be moved into the reconciler state, which currently holds the following: `(:normalized :remove :queue :sends-queued :queued-sends :queued :render :root :t :target)`  

Nothing is breaking, but I don't think the reconciler should be making changes to the user's application state.  Especially if you are supplying datascript for the state.  Making changes on the application state could lead to unspecified future problems.  I think only merge!, set-query! and get-local-query-data would need to be changed.

**Comment by swannodette** [comment]
This is subsumed by some other work.
