### ISSUE TITLE
react.inc.js:18780 when running examples/counters

### ISSUE THREAD

**Issue by ndroock1** [omcljs/om#669]
I newbie forked omcljs/om, imported it in IntelliJ/IDEA with Cursive plugin and opened index.html in examples/counters in chrome. The React plugin in Chrome Developer tools reported many warnings starting with:
react.inc.js:18780 Warning: A component is accessing isMounted inside its render() function. render() should be a pure function of props and state. 
That said, the component works but slow, update of the counter takes > 2 sec and sometimes clicks are not processed.

**Comment by swannodette** [comment]
Please ask questions on the Om slack channel. Thanks.
