### ISSUE TITLE
Updated docs for Links

### ISSUE THREAD

**Issue by kendagriff** [omcljs/om#670]
I followed [this article on links](https://github.com/omcljs/om/wiki/Thinking-With-Links%21), only to discover after *lots* of hair pulling, that the `alpha22` release pointed to in the [Quick Start](https://github.com/omcljs/om/wiki/Quick-Start-%28om.next%29) article is not up-to-date.

What's the best way to address that? Make a clearer note in the Links article that they're not the same version, or update the Quick Start guide?

**Comment by swannodette** [comment]
Just fix the Quick Start guide in this case. Thanks.
