### ISSUE TITLE
Initial state not passed to component on load

### ISSUE THREAD

**Issue by gaye** [omcljs/om#674]
I'm running into a weird issue on `1.0.0-alpha32` where a component's input value, which should be provided by the reconciler, is initially `null` (it should be a string from the initial state). As soon as I begin typing, my mutation function gets applied correctly, but typing "abc" gives "abc" instead of "some initial valueabc". Is this a known issue?

**Comment by gaye** [comment]
Would it help if I added a minimal reproduction?

**Comment by anmonteiro** [comment]
Happy to look at a minimal case, as I can't really tell anything from the description

**Comment by gaye** [comment]
Curiously the bug went away when I tried to build a minimal test case. Sorry to bother!

**Comment by gaye** [comment]
So I found out that this only happens when I have a non-root component with a query. There's a pared down, two component example here https://github.com/gaye/om-issue-674 . Thanks for your help @anmonteiro!

**Comment by gaye** [comment]
The second commit 0de9a71424a8b762283fc9356cc65d147bfcb7cf introduces the bug -- namely that the textbox no longer displays the initial text "Can you see me?".

**Comment by anmonteiro** [comment]
The example is invalid, this is a non-issue.
Component queries must compose to the root.
If you have any questions regarding what this means, come ask them in the Clojurians slack, #om channel
