### ISSUE TITLE
set-query! with params for non-root components does not trigger remote read merge.

### ISSUE THREAD

**Issue by dimitertodorov** [omcljs/om#675]
Please let me know if I am doing something incorrect,
See the following repo for code exhibiting the problem.
https://github.com/dimitertodorov/booty/blob/master/src/cljs/booty/core.cljs

Taking the Autocompleter example, I tried nesting the AutoCompleter below the root, expecting it to behave the same.

When the component first loads, I want to trigger a remote read with the :query param set to "Dimiters". In the case below, 
I can see the remote HTTP call, and the results are received back.
However they are not merged back into the component's state.
If I type text into the field, the component updates, but it appears that the state of the local component is 1 behind the desired merged state.

If I render AutoCompleter directly as the root, the problem does not occur.

```clj
(defui AutoCompleter
  static om/IQueryParams
  (params [_]
    {:query ""})
  static om/IQuery
  (query [_]
    '[(:search/results {:query ?query})])
  Object
  (componentWillMount [this]
    (om/set-query! this {:params {:query "Dimiters"}}))
  (render [this]
    (let [{:keys [search/results]} (om/props this)]
      (dom/div nil
               (dom/h2 nil "Autocompleter")
               (cond->
                 [(search-field this (:query (om/get-params this)))]
                 (not (empty? results)) (conj (result-list results)))))))
(defui Root
  Object
  (render [this]
    (dom/div nil
             ((om/factory AutoCompleter)))))
```

**Comment by dimitertodorov** [comment]
So, did some more testing, it looks like the local component state is getting the properties, but for whatever reason a render is not being triggered.

To test this, added a simple button to update/set some unrelated component state key.
As soon as that button is clicked, the correct remote data is rendered.

```clojure
(defui AutoCompleter
  static om/IQueryParams
  (params [_]
    {:query ""})
  static om/IQuery
  (query [_]
    '[(:search/results {:query ?query})])
  Object
  (componentWillMount [this]
    (om/set-query! this {:params {:query "Dimiters"}}))
  (render [this]
    (let [{:keys [search/results]} (om/props this)]
      (dom/div nil
               (dom/h2 nil "Autocompleter")
               (cond->
                 [(search-field this (:query (om/get-params this)))]
                 (not (empty? results)) (conj (result-list results)))
               (dom/div nil
                 (dom/button #js {:onClick #(om/update-state! this :random/key "Random")} "X"))))))
```

**Comment by anmonteiro** [comment]
This is a non-issue. The example is incorrect because the query doesn't compose to the root.
