### ISSUE TITLE
Error on recursive component state update

### ISSUE THREAD

**Issue by Artesonraju** [omcljs/om#676]
When calling om/update-state! on a recursive component (deep enough) :

`Error: No queries exist for component path (client.main/CompositeApp client.main/Component) or data path [:composite/item :children :children]`

Example gist inspired from @anmonteiro's [composite.cljs](https://gist.github.com/anmonteiro/2b282aa35380558a8b1d), click one of the two top squares to trigger the error : https://gist.github.com/Artesonraju/3459f00a76d5b853aa08265baf4603a9

**Comment by anmonteiro** [comment]
This is a regression of the dynamic queries patch. PR #677 fixes the issue.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/d88bcde7ae1a8d8a778fb4edb3448bcc09742796
