### ISSUE TITLE
Why we can retrieve atom contents via (seq (:entries my-atom)) in component constructor?

### ISSUE THREAD

**Issue by xfcjscn** [omcljs/om#678]
I passed an atom: `(defonce tasklist-atom (atom {:entries []}))` to om/root function: `(om/root tasklist tasklist-atom {:target tasklistel})`

Now I can retrieve the atom content inside component constructor like this: `(seq (:entries @tasklist-atom))` or `(seq (:entries tasklist-atom))` . It should be an issue that I can retrieve the atom content via: `(seq (:entries tasklist-atom))` right?

Component Constructor Code Example:

	(defn render-tasklist
	  [state owner {:keys [counter] :as local}]
	  (println (seq (:entries state)))    ;; print ({:subject "a", :id 2, :completed false})
	  (println (seq (:entries @state)))    ;; print ({:subject "a", :id 2, :completed false})

**Comment by swannodette** [comment]
Please ask questions in the Slack channel or #clojurescript IRC before opening issues that are questions. Thanks much.
