### ISSUE TITLE
:query-root true disappears somewhere between read and send function

### ISSUE THREAD

**Issue by jasonjckn** [omcljs/om#684]
Setting `:query-root` to true in AST has no effect on the query expression passed to send function. It should contain meta data ^{:query-root true} on the inner join in this case but it doesn't. Consequently `om/process-roots` does not reroot the query. 

```clojure
(defmethod remote-read :widget/two
  [{:keys [state query ast target] :as env} key _]
  {target (assoc-in ast [:children 0 :query-root] true)})

(defn send [{:keys [remote]} cb]
  (println "SEND query: " (prn-str remote))
  (postwalk (fn [xf]
              (if (map? xf)
                (do (println "meta: " (prn-str (or (meta xf) {})))
                    xf)
                xf
                )) remote)
  (let [{:keys [query rewrite]} (om/process-roots remote)]
    (println "query: " (prn-str query))
    (println "rewrite: " (rewrite {:datomic/pull [{:listing/title "foobar!"}]}))
    ))
```

The output from this is 
```
SEND query:  [{:widget/two [{:datomic/pull [:listing/title]}]}]
meta:  {}
meta:  {}
query:  [{:widget/two [{:datomic/pull [:listing/title]}]}]
rewrite:  {:datomic/pull [{:listing/title foobar!}]}
```

**Comment by jasonjckn** [comment]
Tom Jack on slack pointed out to me that AST children is read-only, and that instead of updating the children, I need to update :query on the root of the AST 

``` (update-in ast [:query 0] vary-meta assoc :query-root true)]```

This fixes the issue, I think the API is very unintuitive here because :query-root is obeyed when it's on the root join, just not when it's in children, I would have expected ast to be totally read-only at all levels, or updatable at all levels of the tree, one or the other. Feel free to close the issue though.

**Comment by swannodette** [comment]
@jasonjckn right probably needs some further thinking through
