### ISSUE TITLE
reconciler? should use implements? rather than instance?

### ISSUE THREAD

**Issue by taylorSando** [omcljs/om#689]
Currently `reconciler?` uses `implements?` as its predicate function.  If you want to allow different reconciler implementations, then this should be `(implements? IReconciler)`

A different reconciler implementation may want to reuse some of the existing code, e.g. `set-query!` However, many of these functions are using `reconciler?` checks, which are tied to the current implementation of the reconciler, rather than the reconciler interface

**Comment by swannodette** [comment]
Ok, but probably will hold off on this one until beta2

**Comment by anmonteiro** [comment]
fixed 7db37212291491448e508e551ddf220ecc7067cd
