### ISSUE TITLE
[next] Exceptions in the client-side :action are discarded during transact!

### ISSUE THREAD

**Issue by mikekap** [omcljs/om#690]
Running ``(om/transact! `[(my-mutation {:foo :bar})])`` where `my-mutation` has an `:action` that throws, results in no messages anywhere about something failing. It would be nice if these were shown somewhere.

**Comment by swannodette** [comment]
We do not discard. We add all errors to the result.

**Comment by mikekap** [comment]
What result is it in? `transact!` doesn't return anything...

**Comment by rhacker** [comment]
@mikekap did you check in app-state ?

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/c47d27c1686ce77a4c3be917078b03b2bc6018e5
