### ISSUE TITLE
om.next/update-query has apply misplaced

### ISSUE THREAD

**Issue by petterik** [omcljs/om#692]
Did: Called `om.next/update-query!` with more than 5 arguments: `(om/update-query! this update :params assoc :foo 1 :bar 2)`

Expected: Query to be updated with params `{:foo 1 :bar 2}`.

Happened: `Error: Assert failed: (or (not (nil? params)) (not (nil? query)))`

Cause: Call to `apply` is misplaced in `om.next/update-query!`:
```clj
  ([component f arg0 arg1 arg2 arg3 & arg-rest]
   (apply set-query! component
     (f {:query  (get-unbound-query component)
         :params (get-params component)}
        arg0 arg1 arg2 arg3 arg-rest))))
```

Solution: Call `apply` on `f` like so:
```clj
  ([component f arg0 arg1 arg2 arg3 & arg-rest]
   (set-query! component
     (apply f {:query  (get-unbound-query component)
               :params (get-params component)}
            arg0 arg1 arg2 arg3 arg-rest))))```

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/1816c7d033ec08b1672b4a1d92fb1a9e93da76f4
