### ISSUE TITLE
componentDidMount, core.async and getElement.

### ISSUE THREAD

**Issue by hlolli** [omcljs/om#693]
I have this code  (using [org.omcljs/om "1.0.0-alpha36"])
```Clojure


(def app-state (atom {:edn/graph []}))


(defui Root
  static om/IQueryParams
  (params [_]
    {:query -1})
  static om/IQuery
  (query [_]
    '[(:edn/graph {:query ?query})])
  Object
  (componentDidMount [this]
    (.addEventListener (gdom/getElement "node4") "mouseover" #(js/alert "hello númer 4"))) ;;;;; <------ node4 not found?
  (render [this]
    (let [{:keys [edn/graph]} (om/props this)]
      (dom/div nil
               (dom/p nil (str (om/get-params this)))
               (dom/button #js {:onClick (fn [_] (om/set-query! this
                                                                {:params
                                                                 {:query
                                                                  (inc
                                                                   (:query (om/get-params this)))}}))} "INC")
               (dom/button #js {:onClick (fn [_] (om/set-query! this
                                                                {:params
                                                                 {:query
                                                                  (dec
                                                                   (:query (om/get-params this)))}}))} "DEC")
               (dom/div #js {:dangerouslySetInnerHTML #js {:__html (get-in graph [:body :svg-graph])}})))))




(defmulti mutate (fn [env k params] k))


(defmulti read om/dispatch)


(defmethod read :edn/graph
  [{:keys [state ast] :as env} k {:keys [query]}]
  (merge
   {:value (get @state k [])}
   {:edn ast}))


(defn graph-query-loop [chn]
  (go
    (loop [[query cb] (<! chn)]
      (let [response (<! (http/get "http://localhost:8080/1142222967602"
                                   {:content-type "application/edn"
                                    :with-credentials? false
                                    :edn-params :body
                                    :query-params {"timetag" query}}))]
        (cb {:edn/graph response}))
      (recur (<! chn)))))


(defn graph-make-query [chn]
  (fn [{:keys [edn]} cb]
    (when edn
      (let [{[edn] :children} (om/query->ast edn)
            query (get-in edn [:params :query])]
        (put! chn [query cb])))))


(def send-chan (chan))


(def parser (om/parser {:read read :mutate mutate}))

(def reconciler
  (om/reconciler {:state app-state
                  :parser parser
                  :send (graph-make-query send-chan)
                  :remotes [:remote :edn]}))


(graph-query-loop send-chan)


(defn init []
  (om/add-root! reconciler Root (gdom/getElement "graphv")))
```

Which gives me in google chrome browser `deferred.js:889 Uncaught TypeError: Cannot read property 'addEventListener' of null`
![git1](https://cloud.githubusercontent.com/assets/6074754/15681862/55fcd784-275b-11e6-9dd2-e6d85d6444df.jpg)

If I comment `;;(.addEventListener (gdom/getElement "node4") "mouseover" #(js/alert "hello númer 4"))` from the `componentDidMount` inside the Root component.

Then everything loads error free (but lacking my ability to target dom elements). 
![git2](https://cloud.githubusercontent.com/assets/6074754/15681873/60f180b8-275b-11e6-9250-45a18f71e290.jpg)

But to prove that `componentDidMount` is actually being called when in fact the component has not mounted, then I can always evaluate `(.addEventListener (gdom/getElement "node4") "mouseover" #(js/alert "hello númer 4"))` in the REPL and get this _(not seen on this photo, then my curser is over one of the box that has the id="node4")_:
![git3](https://cloud.githubusercontent.com/assets/6074754/15681881/67cc3572-275b-11e6-9f15-edd1099437ff.jpg)

So, am I doing something wrong or is om.next prematurely running `gdom/getElement` despite the component is still in the process of mounting the svg that is being fetch from other local backend?

**Comment by swannodette** [comment]
This is a question, please ask on the #om Slack channel thanks.

**Comment by hlolli** [comment]
Ok, found this out in the end. If someone is interested in how I solved this, then I made this simple go loop in `componentDidMount`

```clojure
(componentDidMount [this]
    (go (while (nil? (gdom/getElement "node4"))
          (<! (timeout 20)))
        (.addEventListener (gdom/getElement "node4") "mouseover" #(js/alert "hello númer 4"))))
```

**Comment by stephenway** [comment]
Ack! Was looking for an answer for this, but now I'm unsure of if it's searchable.

**Comment by hlolli** [comment]
The answer is (maybe strangely) to use componentDidUpdate instead of componentDidMount, so this is a react.js caveat.
