### ISSUE TITLE
db->tree uses the wrong ident namespace when following an ident chain to an Union

### ISSUE THREAD

**Issue by wilkerlucio** [omcljs/om#710]
```clojure
(let [data {:a [:b 1]
            :b {1 [:c 2]}
            :c {2 {:foo "bar" :x "y"}}}]
  (om/db->tree [{:a {:b [:x] :c [:foo]}}]
               data
               data))
```

Expected output: `{:a {:foo "bar}}`
Actual output: `{:a {:x "y"}}`

It seems to be following the chain `[:b 1] [:c 2]`, but when it tries to resolve the union it's using the `[:b 1]` (the first ident) to select the union target instead of `[:c 2]` (the last, which would be the expected IMHO).

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/00157c95604830507d0320602e6133089d0926a6
