### ISSUE TITLE
om.next `getInitialState` callback handler never seems to be invoked in the react lifecycle

### ISSUE THREAD

**Issue by bjconlan** [omcljs/om#712]
When attempting to render the component
```
;; component example taken from https://github.com/omcljs/om/issues/452
(defui MyView
  Object
  (getInitialState [this] {:test "here!"})
  (render [this] (dom/div nil (:test (om/get-state this)))))
```
The getInitialState callback handler never seems to be invoked in the react lifecycle.

This was tested against `cljsjs/react "15.0.2-0"` using both `org.omcljs/om "1.0.0-alpha34"` and `org.omcljs/om "1.0.0-alpha37"`

In the mean time `componentWillMount` fulfills my requirements.

**Comment by anmonteiro** [comment]
You want to use `initLocalState` instead

**Comment by bjconlan** [comment]
Ah thank you.
