### ISSUE TITLE
process-roots fails when recursive queries are outside of a query-root.

### ISSUE THREAD

**Issue by cmcfarlen** [omcljs/om#713]
I ran into an issue with process-roots and recursive queries.  In my case, I have a query that has both a query-root and a recursive query that was outside of the query root (in another part of the query).  I was getting an exception when calling process roots.  I tracked down the issue and created this pr to address it.  The problem was trying to `mapcat` over the `join-value` which in the recursive case is the symbol `'...`   I also added a test for this case.

PR here: https://github.com/omcljs/om/pull/691

**Comment by anmonteiro** [comment]
fixed https://github.com/omcljs/om/commit/3e0e705f08cfc469dfe16d254c68aa762231644e
