### ISSUE TITLE
Problem with om tutorial - only one (top) entry visible

### ISSUE THREAD

**Issue by zygm0nt** [omcljs/om#726]
Hi, I'm going through Om basic tutorial (https://github.com/omcljs/om/wiki/Basic-Tutorial), now at "Higher Order Components".  

I always see only single entry from the dataset, the top one. Is this some known issue? I can't find any difference in what I've written and what's in the tutorial, so could you point me to the right place? I've pasted this code into a Gist: https://gist.github.com/zygm0nt/4f27cb733552f79ccf31257185b95143

Also I had to set app-state from `def` to `defonce` for the page to actually display anything. Before that I got only this kind of error:

```
Error: Assert failed: No target specified to om.core/root
(not (nil? target))
```

**Comment by devm33** [comment]
Hey @zygm0nt I am also having issues with the tutorial.

I am getting the error `React.render is not a function`. I suspect this might have to do with versions of something, but I am getting that on the `lein new figwheel` project as is.

Did you have this same issue and if so were you able to get past it?

Thanks!

**Comment by anmonteiro** [comment]
@zygm0nt you most likely don't have an element with the ID "registry" in your HTML.

@devm33 should be a conflict with React versions. If you're trying to use `om.core` with a React version newer to 0.14 you should be using a newer Om version as well. latest alphas work with `om.core` just fine.

**Comment by zygm0nt** [comment]
@anmonteiro okey, this seemed to be a glitch, because running this code fresh today, after your message proved it works - the mentioned error is gone. But do you know why there is only one entry presented? I can't figure this out.

**Comment by anmonteiro** [comment]
@zygm0nt questions like this should be asked in the clojurians Slack, #om channel.
