### ISSUE TITLE
allow `:private` metadata in `defui`

### ISSUE THREAD

**Issue by anmonteiro** [omcljs/om#739]
just like `^:once`, it should be possible to define private components `(defui ^:private Foo)`

**Comment by swannodette** [comment]
This sounds interesting but it's harder for me to see the value of private components than the value of private fns in some API. More rationale here?

**Comment by anmonteiro** [comment]
IMHO, if we're abstracting over defining vars with `defui`, it should be possible for users to control if the generated var is public or private.

My specific use case for this would be that in some cases I don't want `ui` to leak a public var into my namespace, which is currently the case.

**Comment by anmonteiro** [comment]
Other use case that calls for more metadata (other than just `:private`) to be supported in the generated `defui` var is for things like generating documentation on namespaces, where you might want to add `:skip-wiki` or `:no-doc` to the var.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/79ab877aa39392105718e810033951eee2a154a0
