### ISSUE TITLE
Docstrings on defui vars would be nice

### ISSUE THREAD

**Issue by Peeja** [omcljs/om#746]
I'd love to be able to add docstrings to defui vars, like so:

```cljs
(defui Widget
  "Presents a handy widget.

  Props:
  :dingbat - (optional) A custom dingbat to display on the whirligig."
  Object
  (render [this]
    …))
```

A string there should otherwise be illegal, so I believe that should be inferable.

**Comment by anmonteiro** [comment]
I agree this would be a nice enhancement.

Extra points for putting the docstring in the generated var's `:docstring` metadata

**Comment by swannodette** [comment]
No argument from me. PR welcome.

**Comment by swannodette** [comment]
fixed https://github.com/omcljs/om/commit/53268aae80c384d22d7b919a8304ea4e9806844b

**Comment by Peeja** [comment]
Many thanks!
