### ISSUE TITLE
Should om.next/children use React.Children.toArray?

### ISSUE THREAD

**Issue by Peeja** [omcljs/om#747]
Currently, `om.next/children` returns `(.. component -props -children)`, which is the opaque structure React uses to implement children. The correct way to iterate over this is with the [`React.Children` API](https://facebook.github.io/react/docs/top-level-api.html#react.children).

If it instead returned `(js/React.Children.toArray (.. component -props -children))`, it would be a real sequence that could be used directly in Clojure-y ways.

**Comment by Peeja** [comment]
(Alternately, it may be preferable to encourage people to use `React.Children.map` to map over children, as it does do some fancy things with keys.)

**Comment by swannodette** [comment]
I thought children were just ES6 iterables these days, perhaps I remember incorrectly?

**Comment by anmonteiro** [comment]
Pretty sure they're iterables too.
Also we use `force-children` so I'm quite certain we can manipulate them with Clojure's data functions.

**Comment by Peeja** [comment]
Yeah, looking closer, I think I misunderstood what's going on. I think there's still something fishy I can't put my finger on, but if so I'll open a new issue when I have more insight.
