### ISSUE TITLE
Incremental rendering in reconcile! throws Index out of bounds

### ISSUE THREAD

**Issue by petterik** [omcljs/om#766]
Updating om from alpha37 to alpha44, I'm getting `Uncaught Error: Index out of bounds` in `cljs.core/subvec` used from `om.next/reconcile!`:
https://github.com/omcljs/om/blob/master/src/main/om/next.cljs#L1832

After doing some printing, I found that `(let [update-path (path c)]` on line 1829, sets `update-path` as  `nil`. 

Facts about the component `c`:
It does not implement `om/IQuery`.
I'm passing its factory `(om/computed {} {..stuff..})`.
It has local state and updates it with `om/update-state!`

Will start working on a repro.

**Comment by wilkerlucio** [comment]
I'm falling in this problem sometimes, but I wasn't able to figure out what's causing it. My component that causes it also doesn't implement `om/IQuery`, and it's on a tree where most of its parents do.

**Comment by petterik** [comment]
Repro commit here:
https://github.com/petterik/om/commit/a989b8691ff4d35d814bc4c6babe003106111da3
Branch:
https://github.com/petterik/om/tree/om-766-devcard

**Comment by petterik** [comment]
Verified on master that has commit 39f68233aab0ef5f38f8e220afed1e7f89190645
