### ISSUE TITLE
Be more permissive for static class methods

### ISSUE THREAD

**Issue by levitanong** [omcljs/om#786]
(afaict, this is specific to defui*-clj. https://github.com/omcljs/om/blob/master/src/main/om/next.cljc#L318)

Currently, if I do the following:
```clj
(defui Component
  static SomeProtocol
  (some-protocol [this] ...))

(meta Component)
;; Will not contain :some-protocol, because it has been filtered out.
```

With a more permissive filter, you can let users extend their components with things like `static IStyle`. This will allow one to have colocated styles and generate stylesheets during compile time instead of runtime.

**Comment by anmonteiro** [comment]
fixed 8c93a1708d772df81df0685af16e0b80d8f73eff
