### ISSUE TITLE
"No queries exist for component path … or data path …" should be "and data path"

### ISSUE THREAD

**Issue by Peeja** [omcljs/om#794]
Unless I'm mistaken, the error [`(str "No queries exist for component path " cp " or data path " path')`](https://github.com/omcljs/om/blob/3a8229c4a843c9978ced8eec94f0fa33ae57b869/src/main/om/next.cljc#L1962) should read "and", not "or". This error is only reached when queries _do_ exist for the component path, but none of those queries matches the data path. When no queries match the _component_ path, [a different error is thrown](https://github.com/omcljs/om/blob/3a8229c4a843c9978ced8eec94f0fa33ae57b869/src/main/om/next.cljc#L1962).

**Comment by anmonteiro** [comment]
Isn't it correct because of the negative form "No"? The opposite would be "there exist queries for the component path and data path". The negative changes the "and" to "or".

Anyway, here's a link that might help us solve this one: http://bikeshed.com/

**Comment by Peeja** [comment]
No, that's not correct. The opposite would be "Some query exists for component path `cp` or data path `path'`."

I believe you're thinking of De Morgan's laws, that "not(A or B)" means "not(A) and not(B)". Here, that says that "No queries exist for component path `cp` or data path `path'`" means the same thing as "No queries exist for component path `cp`, *and* no queries exist for data path `path'`". The first part of that statement is false: a query does exist for the component path.

This isn't bikeshedding; the error message is lying, and I wasted a fair bit of time trying to understand what was going on because I believed it.

**Comment by anmonteiro** [comment]
@Peeja that's right, I get it now. The error message should be improved.

**Comment by anmonteiro** [comment]
fixed https://github.com/omcljs/om/commit/e1b94045b5ec48a601df2dc2a8e7312c0e96d771
