### ISSUE TITLE
Issues in 1.9.293

### ISSUE THREAD

**Issue by EmergentBehavior** [omcljs/om#812]
When upgrading to the latest version of ClojureScript I encountered two errors when testing my project via Figwheel. Received an `invariant violation`: error indicated this was caused by called `om.transact` on a component that did not (or parent did not) implement IQuery. This is not the case and code works fine in previous version of ClojureScript.

Additionally, an initial read query that usually occurs on one of my components does not when bumping up to 1.9.293.

I can give more details later when I have time but wanted to put this out there in case anyone else encountered similar issues with 1.9.293.

**Comment by anmonteiro** [comment]
You need to be on Om 1.0.0-alpha47 when upgrading to ClojureScript 1.9.293. I suspect that's what's going wrong.

**Comment by EmergentBehavior** [comment]
@anmonteiro That makes sense, thanks. I think I missed it because it wasn't visible in the Github releases but I see it in Clojars.
