### ISSUE TITLE
send-cb should use reconcile!

### ISSUE THREAD

**Issue by julienfantin** [omcljs/om#820]
The `send-cb` fn in the reconciler's `add-root!` is implemented with `merge!`. 

This forces the app to re-render from the root regardless of the result and/or the query being merged.

This could be prevented by implementing `send-cb` with `reconcile!` instead.

**Comment by swannodette** [comment]
Thanks for the report. I think can be easily solved with a queue but for remotes.

**Comment by swannodette** [comment]
@julienfantin I pushed a potential fix to master, please test. Thanks.

**Comment by julienfantin** [comment]
Just reporting that these changes have been working well for us 👍

For anyone looking, the commits are around: 74549c287930c4afa359b9c8f3fc18cd19834d73
