### ISSUE TITLE
refactor om.next/denormalize*

### ISSUE THREAD

**Issue by ftravers** [omcljs/om#831]
try to instrument this function with cider debugger throws a "method too large" error.  Can it be refactored into smaller chunks so users can instrument and learn better how the function works?  I'm having an issue with the function that no one is responding to on slack, so would like to find the problem myself without have to pepper the code with `println`s.

**Comment by swannodette** [comment]
This just sounds like a issue with how cider debugger works. This needs to be taken up elsewhere.
