### ISSUE TITLE
om.next (dom/render-to-str (component initial-data)) throws ReactDOMServer undefined

### ISSUE THREAD

**Issue by sova** [omcljs/om#837]
nf-starter-january.core=> (dom/render-to-str (blurb boo))

#object[ReferenceError ReferenceError: ReactDOMServer is not defined]
ReferenceError: ReactDOMServer is not defined

[org.omcljs/om "1.0.0-alpha45"]

(it could just be an error on my part, but perhaps someone more experienced can take a look.)

**Comment by anmonteiro** [comment]
If you want to use `om.dom/render-to-str` on the CLJS side you need to include a deendency on `ReactDOMServer` in your project and require it. Om doesn't bundle `ReactDOMServer` since it's an optional feature which isn't very used.

**Comment by sova** [comment]
I want to use it is so I can render pages on the server-side in a server.clj file.

Is it possible to include the cljs dependency [cljsjs.react.dom.server] in a Clojure file?

Thanks

**Comment by anmonteiro** [comment]
If you're trying to use `om.dom/render-to-str` from Clojure you don't need a `ReactDOMServer` dependency. You certainly didn't get that error from Clojure, since what you pasted originally is a JavaScript error.

**Comment by sova** [comment]
You are right, that was a js error, not a clojure one.

Strangely now, though, "CompilerException java.lang.RuntimeException: Unable to resolve symbol: defui in this context" ... Perhaps I am missing something fundamental about including om dependencies in a clj file.  

I was assuming I could drop-in all my ui bits (defui, om/factory) and (dom/render-to-str ...) within a clj file.  Is this approach misguided?
