### ISSUE TITLE
status of server side rendering in Om Next

### ISSUE THREAD

**Issue by jtmarmon** [omcljs/om#838]
Under "Om Next Design" there's a section for server side rendering:
![image](https://cloud.githubusercontent.com/assets/4528076/21769594/dbcfd8a8-d655-11e6-9b7e-21076b4f4efc.png)

Read the doc and you'll find that Om Next doesn't support SSR by default. 

I looked into what it would take to support this in core, and found that in theory SSR is supported by default in Om Next: https://github.com/arohner/foam/issues/1

> as of omcljs/om#764 and 1.0.0-alpha45, Om Next now has builtin support for server-side rendering. 🎉

I'm guessing it was a mistake to file the Server Side Rendering doc under Om Next design, and that Om Next is simply missing documentation on SSR?

**Comment by anmonteiro** [comment]
Right, the document is most likely outdated. Every other resource you linked is indeed correct, and server-side rendering is a part of Om Next as of 1.0.0-alpha45.

Here's a repository I put together around that time showing off how to take advantage of this feature:

https://github.com/anmonteiro/om-next-fullstack

**Comment by jtmarmon** [comment]
awesome, thanks for the confirmation @anmonteiro. this project looks great.
