### ISSUE TITLE
Typo in om.next tutorial

### ISSUE THREAD

**Issue by flyjwayur** [omcljs/om#846]
Found a typo in [om.next tutorial](https://github.com/omcljs/om/wiki/Quick-Start-(om.next))
I'd make a fix myself, but I didn't sign electronic Contributor Agreement and I assume it won't be easy to be accepted. So just making an issue here.

> A parser is created from two functions that provides semantics for
> reads and mutations:

I'd suggest that we change this part like this
"A parser is created from two functions that _**provide**_ ..."

Because of consistent use of verb (provides -> provide) with the plural form(functions).
(Actually I was able to edit the page myself, I expected that is not allowed to me though.)

**Comment by flyjwayur** [comment]
I was able to edit techwiki myself, I didn't know I could. Now I am worried if it was ok to edit the page without permission, but as it was a minor typo fix, hopefully everything's OK.

**Comment by swannodette** [comment]
@flyjwayur that change is OK! Thanks
