### ISSUE TITLE
SSR react checksum warning for equal markup

### ISSUE THREAD

**Issue by petterik** [omcljs/om#851]
Did: Used om.dom for server and client side rendering.

Happened: 
-  Got react warning: "Warning: React attempted to reuse markup in a container but the checksum was invalid. [...]"
-  Browser jumped to top of the page.

Expected: React to not print the warning, as the server and client side render the same markup.

**Comment by petterik** [comment]
I narrowed the warning down to this minimal case:
```clj
(defui SSRBug
  Object
  (render [this]
    (dom/div
      #js {:style #js {:backgroundImage "&"}})))
```

Fixes warnings for me by escaping string values in the `:styles` map in om.dom:
https://github.com/omcljs/om/blob/master/src/main/om/dom.cljc#L468

**Comment by anmonteiro** [comment]
fixed https://github.com/omcljs/om/commit/8730bbd9140a9ecd364904c4e464a0d9bf533284
